#!/bin/bash

if [ "$0" = "bash" ];then
  echo $0
  make ui-requirements
fi

make clean || { echo "Make clean failed, please deal with error"; exit $ERRCODE; }

make ui/build || { make ui/build_dep; make ui/build; } || { echo "Make ui/build failed, please deal with error"; exit $ERRCODE; }

make build || { echo "Make build failed, please deal with error"; exit $ERRCODE; }

/lora-app-server/build/lora-app-server -c configuration/lora-app-server.toml

