// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fuotaDeployment.proto

package appserver_serves_ui

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FUOTADeploymentDeviceState int32

const (
	// Pending.
	FUOTADeploymentDeviceState_PENDING FUOTADeploymentDeviceState = 0
	// Success.
	FUOTADeploymentDeviceState_SUCCESS FUOTADeploymentDeviceState = 1
	// Error.
	FUOTADeploymentDeviceState_ERROR FUOTADeploymentDeviceState = 2
)

var FUOTADeploymentDeviceState_name = map[int32]string{
	0: "PENDING",
	1: "SUCCESS",
	2: "ERROR",
}

var FUOTADeploymentDeviceState_value = map[string]int32{
	"PENDING": 0,
	"SUCCESS": 1,
	"ERROR":   2,
}

func (x FUOTADeploymentDeviceState) String() string {
	return proto.EnumName(FUOTADeploymentDeviceState_name, int32(x))
}

func (FUOTADeploymentDeviceState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4f4a0a6fe690dc29, []int{0}
}

type FUOTADeployment struct {
	// ID of the deployment (string formatted UUID).
	// This value will be automatically assigned on create.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name of the deployment.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Multicast type.
	// Currently only Class-C is supported!
	GroupType MulticastGroupType `protobuf:"varint,3,opt,name=group_type,json=groupType,proto3,enum=appserver_serves_ui.MulticastGroupType" json:"group_type,omitempty"`
	// Data-rate.
	Dr uint32 `protobuf:"varint,4,opt,name=dr,proto3" json:"dr,omitempty"`
	// Frequency (Hz).
	Frequency uint32 `protobuf:"varint,5,opt,name=frequency,proto3" json:"frequency,omitempty"`
	// Payload.
	Payload []byte `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	// Redundancy (number of packages).
	Redundancy uint32 `protobuf:"varint,7,opt,name=redundancy,proto3" json:"redundancy,omitempty"`
	// Multicast time-out.
	// Please refer to the Remote Multicast Setup specification as this field
	// has a different meaning for Class-B and Class-C groups.
	MulticastTimeout uint32 `protobuf:"varint,8,opt,name=multicast_timeout,json=multicastTimeout,proto3" json:"multicast_timeout,omitempty"`
	// Unicast time-out.
	// Set this to the value in which you at least expect an uplink frame from the
	// device. The FUOTA deployment engine will wait at least for the given time
	// before proceeding with the next steps.
	UnicastTimeout *duration.Duration `protobuf:"bytes,9,opt,name=unicast_timeout,json=unicastTimeout,proto3" json:"unicast_timeout,omitempty"`
	// Deployment state.
	// This value will be automatically set on create.
	State string `protobuf:"bytes,10,opt,name=state,proto3" json:"state,omitempty"`
	// Next step after.
	// This value will be automatically set on create.
	NextStepAfter        *timestamp.Timestamp `protobuf:"bytes,11,opt,name=next_step_after,json=nextStepAfter,proto3" json:"next_step_after,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FUOTADeployment) Reset()         { *m = FUOTADeployment{} }
func (m *FUOTADeployment) String() string { return proto.CompactTextString(m) }
func (*FUOTADeployment) ProtoMessage()    {}
func (*FUOTADeployment) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f4a0a6fe690dc29, []int{0}
}

func (m *FUOTADeployment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FUOTADeployment.Unmarshal(m, b)
}
func (m *FUOTADeployment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FUOTADeployment.Marshal(b, m, deterministic)
}
func (m *FUOTADeployment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FUOTADeployment.Merge(m, src)
}
func (m *FUOTADeployment) XXX_Size() int {
	return xxx_messageInfo_FUOTADeployment.Size(m)
}
func (m *FUOTADeployment) XXX_DiscardUnknown() {
	xxx_messageInfo_FUOTADeployment.DiscardUnknown(m)
}

var xxx_messageInfo_FUOTADeployment proto.InternalMessageInfo

func (m *FUOTADeployment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FUOTADeployment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FUOTADeployment) GetGroupType() MulticastGroupType {
	if m != nil {
		return m.GroupType
	}
	return MulticastGroupType_CLASS_C
}

func (m *FUOTADeployment) GetDr() uint32 {
	if m != nil {
		return m.Dr
	}
	return 0
}

func (m *FUOTADeployment) GetFrequency() uint32 {
	if m != nil {
		return m.Frequency
	}
	return 0
}

func (m *FUOTADeployment) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *FUOTADeployment) GetRedundancy() uint32 {
	if m != nil {
		return m.Redundancy
	}
	return 0
}

func (m *FUOTADeployment) GetMulticastTimeout() uint32 {
	if m != nil {
		return m.MulticastTimeout
	}
	return 0
}

func (m *FUOTADeployment) GetUnicastTimeout() *duration.Duration {
	if m != nil {
		return m.UnicastTimeout
	}
	return nil
}

func (m *FUOTADeployment) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *FUOTADeployment) GetNextStepAfter() *timestamp.Timestamp {
	if m != nil {
		return m.NextStepAfter
	}
	return nil
}

type FUOTADeploymentListItem struct {
	// ID of the deployment (string formatted UUID).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Created at timestamp.
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp.
	UpdatedAt *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Name of the deployment.
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// Deployment state.
	State string `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	// Next step after.
	NextStepAfter        *timestamp.Timestamp `protobuf:"bytes,6,opt,name=next_step_after,json=nextStepAfter,proto3" json:"next_step_after,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FUOTADeploymentListItem) Reset()         { *m = FUOTADeploymentListItem{} }
func (m *FUOTADeploymentListItem) String() string { return proto.CompactTextString(m) }
func (*FUOTADeploymentListItem) ProtoMessage()    {}
func (*FUOTADeploymentListItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f4a0a6fe690dc29, []int{1}
}

func (m *FUOTADeploymentListItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FUOTADeploymentListItem.Unmarshal(m, b)
}
func (m *FUOTADeploymentListItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FUOTADeploymentListItem.Marshal(b, m, deterministic)
}
func (m *FUOTADeploymentListItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FUOTADeploymentListItem.Merge(m, src)
}
func (m *FUOTADeploymentListItem) XXX_Size() int {
	return xxx_messageInfo_FUOTADeploymentListItem.Size(m)
}
func (m *FUOTADeploymentListItem) XXX_DiscardUnknown() {
	xxx_messageInfo_FUOTADeploymentListItem.DiscardUnknown(m)
}

var xxx_messageInfo_FUOTADeploymentListItem proto.InternalMessageInfo

func (m *FUOTADeploymentListItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FUOTADeploymentListItem) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *FUOTADeploymentListItem) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *FUOTADeploymentListItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FUOTADeploymentListItem) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *FUOTADeploymentListItem) GetNextStepAfter() *timestamp.Timestamp {
	if m != nil {
		return m.NextStepAfter
	}
	return nil
}

type CreateFUOTADeploymentForDeviceRequest struct {
	// Device EUI (HEX encoded).
	DevEui string `protobuf:"bytes,1,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	// FUOTA deployment.
	FuotaDeployment      *FUOTADeployment `protobuf:"bytes,2,opt,name=fuota_deployment,json=fuotaDeployment,proto3" json:"fuota_deployment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreateFUOTADeploymentForDeviceRequest) Reset()         { *m = CreateFUOTADeploymentForDeviceRequest{} }
func (m *CreateFUOTADeploymentForDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*CreateFUOTADeploymentForDeviceRequest) ProtoMessage()    {}
func (*CreateFUOTADeploymentForDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f4a0a6fe690dc29, []int{2}
}

func (m *CreateFUOTADeploymentForDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFUOTADeploymentForDeviceRequest.Unmarshal(m, b)
}
func (m *CreateFUOTADeploymentForDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFUOTADeploymentForDeviceRequest.Marshal(b, m, deterministic)
}
func (m *CreateFUOTADeploymentForDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFUOTADeploymentForDeviceRequest.Merge(m, src)
}
func (m *CreateFUOTADeploymentForDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_CreateFUOTADeploymentForDeviceRequest.Size(m)
}
func (m *CreateFUOTADeploymentForDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFUOTADeploymentForDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFUOTADeploymentForDeviceRequest proto.InternalMessageInfo

func (m *CreateFUOTADeploymentForDeviceRequest) GetDevEui() string {
	if m != nil {
		return m.DevEui
	}
	return ""
}

func (m *CreateFUOTADeploymentForDeviceRequest) GetFuotaDeployment() *FUOTADeployment {
	if m != nil {
		return m.FuotaDeployment
	}
	return nil
}

type CreateFUOTADeploymentForDeviceResponse struct {
	// ID of the created deployment (string formatted UUID).
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFUOTADeploymentForDeviceResponse) Reset() {
	*m = CreateFUOTADeploymentForDeviceResponse{}
}
func (m *CreateFUOTADeploymentForDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*CreateFUOTADeploymentForDeviceResponse) ProtoMessage()    {}
func (*CreateFUOTADeploymentForDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f4a0a6fe690dc29, []int{3}
}

func (m *CreateFUOTADeploymentForDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFUOTADeploymentForDeviceResponse.Unmarshal(m, b)
}
func (m *CreateFUOTADeploymentForDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFUOTADeploymentForDeviceResponse.Marshal(b, m, deterministic)
}
func (m *CreateFUOTADeploymentForDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFUOTADeploymentForDeviceResponse.Merge(m, src)
}
func (m *CreateFUOTADeploymentForDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_CreateFUOTADeploymentForDeviceResponse.Size(m)
}
func (m *CreateFUOTADeploymentForDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFUOTADeploymentForDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFUOTADeploymentForDeviceResponse proto.InternalMessageInfo

func (m *CreateFUOTADeploymentForDeviceResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetFUOTADeploymentRequest struct {
	// ID of the deployment (string formatted UUID).
	// This value will be automatically assigned on create.
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFUOTADeploymentRequest) Reset()         { *m = GetFUOTADeploymentRequest{} }
func (m *GetFUOTADeploymentRequest) String() string { return proto.CompactTextString(m) }
func (*GetFUOTADeploymentRequest) ProtoMessage()    {}
func (*GetFUOTADeploymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f4a0a6fe690dc29, []int{4}
}

func (m *GetFUOTADeploymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFUOTADeploymentRequest.Unmarshal(m, b)
}
func (m *GetFUOTADeploymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFUOTADeploymentRequest.Marshal(b, m, deterministic)
}
func (m *GetFUOTADeploymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFUOTADeploymentRequest.Merge(m, src)
}
func (m *GetFUOTADeploymentRequest) XXX_Size() int {
	return xxx_messageInfo_GetFUOTADeploymentRequest.Size(m)
}
func (m *GetFUOTADeploymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFUOTADeploymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFUOTADeploymentRequest proto.InternalMessageInfo

func (m *GetFUOTADeploymentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetFUOTADeploymentResponse struct {
	FuotaDeployment *FUOTADeployment `protobuf:"bytes,1,opt,name=fuota_deployment,json=fuotaDeployment,proto3" json:"fuota_deployment,omitempty"`
	// Created at timestamp.
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp.
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetFUOTADeploymentResponse) Reset()         { *m = GetFUOTADeploymentResponse{} }
func (m *GetFUOTADeploymentResponse) String() string { return proto.CompactTextString(m) }
func (*GetFUOTADeploymentResponse) ProtoMessage()    {}
func (*GetFUOTADeploymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f4a0a6fe690dc29, []int{5}
}

func (m *GetFUOTADeploymentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFUOTADeploymentResponse.Unmarshal(m, b)
}
func (m *GetFUOTADeploymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFUOTADeploymentResponse.Marshal(b, m, deterministic)
}
func (m *GetFUOTADeploymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFUOTADeploymentResponse.Merge(m, src)
}
func (m *GetFUOTADeploymentResponse) XXX_Size() int {
	return xxx_messageInfo_GetFUOTADeploymentResponse.Size(m)
}
func (m *GetFUOTADeploymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFUOTADeploymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFUOTADeploymentResponse proto.InternalMessageInfo

func (m *GetFUOTADeploymentResponse) GetFuotaDeployment() *FUOTADeployment {
	if m != nil {
		return m.FuotaDeployment
	}
	return nil
}

func (m *GetFUOTADeploymentResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *GetFUOTADeploymentResponse) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type ListFUOTADeploymentRequest struct {
	// Max number of deployments to return in the result-set.
	Limit int64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// Offset in the result-set (for pagination).
	Offset int64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// Application ID to filter on (optional).
	ApplicationId int64 `protobuf:"varint,3,opt,name=application_id,json=applicationID,proto3" json:"application_id,omitempty"`
	// Device EUI (HEX encoded) (optional).
	DevEui               string   `protobuf:"bytes,4,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListFUOTADeploymentRequest) Reset()         { *m = ListFUOTADeploymentRequest{} }
func (m *ListFUOTADeploymentRequest) String() string { return proto.CompactTextString(m) }
func (*ListFUOTADeploymentRequest) ProtoMessage()    {}
func (*ListFUOTADeploymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f4a0a6fe690dc29, []int{6}
}

func (m *ListFUOTADeploymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFUOTADeploymentRequest.Unmarshal(m, b)
}
func (m *ListFUOTADeploymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFUOTADeploymentRequest.Marshal(b, m, deterministic)
}
func (m *ListFUOTADeploymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFUOTADeploymentRequest.Merge(m, src)
}
func (m *ListFUOTADeploymentRequest) XXX_Size() int {
	return xxx_messageInfo_ListFUOTADeploymentRequest.Size(m)
}
func (m *ListFUOTADeploymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFUOTADeploymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListFUOTADeploymentRequest proto.InternalMessageInfo

func (m *ListFUOTADeploymentRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListFUOTADeploymentRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListFUOTADeploymentRequest) GetApplicationId() int64 {
	if m != nil {
		return m.ApplicationId
	}
	return 0
}

func (m *ListFUOTADeploymentRequest) GetDevEui() string {
	if m != nil {
		return m.DevEui
	}
	return ""
}

type ListFUOTADeploymentResponse struct {
	// Total number of deployments available within the result-set.
	TotalCount int64 `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	// Deployments within this result-set.
	Result               []*FUOTADeploymentListItem `protobuf:"bytes,2,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ListFUOTADeploymentResponse) Reset()         { *m = ListFUOTADeploymentResponse{} }
func (m *ListFUOTADeploymentResponse) String() string { return proto.CompactTextString(m) }
func (*ListFUOTADeploymentResponse) ProtoMessage()    {}
func (*ListFUOTADeploymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f4a0a6fe690dc29, []int{7}
}

func (m *ListFUOTADeploymentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFUOTADeploymentResponse.Unmarshal(m, b)
}
func (m *ListFUOTADeploymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFUOTADeploymentResponse.Marshal(b, m, deterministic)
}
func (m *ListFUOTADeploymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFUOTADeploymentResponse.Merge(m, src)
}
func (m *ListFUOTADeploymentResponse) XXX_Size() int {
	return xxx_messageInfo_ListFUOTADeploymentResponse.Size(m)
}
func (m *ListFUOTADeploymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFUOTADeploymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListFUOTADeploymentResponse proto.InternalMessageInfo

func (m *ListFUOTADeploymentResponse) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *ListFUOTADeploymentResponse) GetResult() []*FUOTADeploymentListItem {
	if m != nil {
		return m.Result
	}
	return nil
}

type ListFUOTADeploymentDevicesRequest struct {
	// ID of the deployment (string formatted UUID).
	// This value will be automatically assigned on create.
	FuotaDeploymentId string `protobuf:"bytes,1,opt,name=fuota_deployment_id,json=fuotaDeploymentID,proto3" json:"fuota_deployment_id,omitempty"`
	// Max number of items to return.
	Limit int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// Offset in the result-set (for pagination).
	Offset               int64    `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListFUOTADeploymentDevicesRequest) Reset()         { *m = ListFUOTADeploymentDevicesRequest{} }
func (m *ListFUOTADeploymentDevicesRequest) String() string { return proto.CompactTextString(m) }
func (*ListFUOTADeploymentDevicesRequest) ProtoMessage()    {}
func (*ListFUOTADeploymentDevicesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f4a0a6fe690dc29, []int{8}
}

func (m *ListFUOTADeploymentDevicesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFUOTADeploymentDevicesRequest.Unmarshal(m, b)
}
func (m *ListFUOTADeploymentDevicesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFUOTADeploymentDevicesRequest.Marshal(b, m, deterministic)
}
func (m *ListFUOTADeploymentDevicesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFUOTADeploymentDevicesRequest.Merge(m, src)
}
func (m *ListFUOTADeploymentDevicesRequest) XXX_Size() int {
	return xxx_messageInfo_ListFUOTADeploymentDevicesRequest.Size(m)
}
func (m *ListFUOTADeploymentDevicesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFUOTADeploymentDevicesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListFUOTADeploymentDevicesRequest proto.InternalMessageInfo

func (m *ListFUOTADeploymentDevicesRequest) GetFuotaDeploymentId() string {
	if m != nil {
		return m.FuotaDeploymentId
	}
	return ""
}

func (m *ListFUOTADeploymentDevicesRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListFUOTADeploymentDevicesRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type GetFUOTADeploymentDeviceRequest struct {
	// ID of the deployment (string formatted UUID).
	// This value will be automatically assigned on create.
	FuotaDeploymentId string `protobuf:"bytes,1,opt,name=fuota_deployment_id,json=fuotaDeploymentID,proto3" json:"fuota_deployment_id,omitempty"`
	// Device EUI (HEX encoded).
	DevEui               string   `protobuf:"bytes,2,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFUOTADeploymentDeviceRequest) Reset()         { *m = GetFUOTADeploymentDeviceRequest{} }
func (m *GetFUOTADeploymentDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*GetFUOTADeploymentDeviceRequest) ProtoMessage()    {}
func (*GetFUOTADeploymentDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f4a0a6fe690dc29, []int{9}
}

func (m *GetFUOTADeploymentDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFUOTADeploymentDeviceRequest.Unmarshal(m, b)
}
func (m *GetFUOTADeploymentDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFUOTADeploymentDeviceRequest.Marshal(b, m, deterministic)
}
func (m *GetFUOTADeploymentDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFUOTADeploymentDeviceRequest.Merge(m, src)
}
func (m *GetFUOTADeploymentDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_GetFUOTADeploymentDeviceRequest.Size(m)
}
func (m *GetFUOTADeploymentDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFUOTADeploymentDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFUOTADeploymentDeviceRequest proto.InternalMessageInfo

func (m *GetFUOTADeploymentDeviceRequest) GetFuotaDeploymentId() string {
	if m != nil {
		return m.FuotaDeploymentId
	}
	return ""
}

func (m *GetFUOTADeploymentDeviceRequest) GetDevEui() string {
	if m != nil {
		return m.DevEui
	}
	return ""
}

type GetFUOTADeploymentDeviceResponse struct {
	DeploymentDevice     *FUOTADeploymentDeviceListItem `protobuf:"bytes,1,opt,name=deployment_device,json=deploymentDevice,proto3" json:"deployment_device,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *GetFUOTADeploymentDeviceResponse) Reset()         { *m = GetFUOTADeploymentDeviceResponse{} }
func (m *GetFUOTADeploymentDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*GetFUOTADeploymentDeviceResponse) ProtoMessage()    {}
func (*GetFUOTADeploymentDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f4a0a6fe690dc29, []int{10}
}

func (m *GetFUOTADeploymentDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFUOTADeploymentDeviceResponse.Unmarshal(m, b)
}
func (m *GetFUOTADeploymentDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFUOTADeploymentDeviceResponse.Marshal(b, m, deterministic)
}
func (m *GetFUOTADeploymentDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFUOTADeploymentDeviceResponse.Merge(m, src)
}
func (m *GetFUOTADeploymentDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_GetFUOTADeploymentDeviceResponse.Size(m)
}
func (m *GetFUOTADeploymentDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFUOTADeploymentDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFUOTADeploymentDeviceResponse proto.InternalMessageInfo

func (m *GetFUOTADeploymentDeviceResponse) GetDeploymentDevice() *FUOTADeploymentDeviceListItem {
	if m != nil {
		return m.DeploymentDevice
	}
	return nil
}

type ListFUOTADeploymentDevicesResponse struct {
	// Total number of devices for the FUOTA deployment.
	TotalCount           int64                            `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Result               []*FUOTADeploymentDeviceListItem `protobuf:"bytes,2,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ListFUOTADeploymentDevicesResponse) Reset()         { *m = ListFUOTADeploymentDevicesResponse{} }
func (m *ListFUOTADeploymentDevicesResponse) String() string { return proto.CompactTextString(m) }
func (*ListFUOTADeploymentDevicesResponse) ProtoMessage()    {}
func (*ListFUOTADeploymentDevicesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f4a0a6fe690dc29, []int{11}
}

func (m *ListFUOTADeploymentDevicesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFUOTADeploymentDevicesResponse.Unmarshal(m, b)
}
func (m *ListFUOTADeploymentDevicesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFUOTADeploymentDevicesResponse.Marshal(b, m, deterministic)
}
func (m *ListFUOTADeploymentDevicesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFUOTADeploymentDevicesResponse.Merge(m, src)
}
func (m *ListFUOTADeploymentDevicesResponse) XXX_Size() int {
	return xxx_messageInfo_ListFUOTADeploymentDevicesResponse.Size(m)
}
func (m *ListFUOTADeploymentDevicesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFUOTADeploymentDevicesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListFUOTADeploymentDevicesResponse proto.InternalMessageInfo

func (m *ListFUOTADeploymentDevicesResponse) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *ListFUOTADeploymentDevicesResponse) GetResult() []*FUOTADeploymentDeviceListItem {
	if m != nil {
		return m.Result
	}
	return nil
}

type FUOTADeploymentDeviceListItem struct {
	// Device EUI (HEX encoded).
	DevEui string `protobuf:"bytes,1,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	// Device name.
	DeviceName string `protobuf:"bytes,2,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// Device state.
	State FUOTADeploymentDeviceState `protobuf:"varint,3,opt,name=state,proto3,enum=appserver_serves_ui.FUOTADeploymentDeviceState" json:"state,omitempty"`
	// Error message (in case of error state).
	ErrorMessage string `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Created at timestamp.
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Updated at timestamp.
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FUOTADeploymentDeviceListItem) Reset()         { *m = FUOTADeploymentDeviceListItem{} }
func (m *FUOTADeploymentDeviceListItem) String() string { return proto.CompactTextString(m) }
func (*FUOTADeploymentDeviceListItem) ProtoMessage()    {}
func (*FUOTADeploymentDeviceListItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f4a0a6fe690dc29, []int{12}
}

func (m *FUOTADeploymentDeviceListItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FUOTADeploymentDeviceListItem.Unmarshal(m, b)
}
func (m *FUOTADeploymentDeviceListItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FUOTADeploymentDeviceListItem.Marshal(b, m, deterministic)
}
func (m *FUOTADeploymentDeviceListItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FUOTADeploymentDeviceListItem.Merge(m, src)
}
func (m *FUOTADeploymentDeviceListItem) XXX_Size() int {
	return xxx_messageInfo_FUOTADeploymentDeviceListItem.Size(m)
}
func (m *FUOTADeploymentDeviceListItem) XXX_DiscardUnknown() {
	xxx_messageInfo_FUOTADeploymentDeviceListItem.DiscardUnknown(m)
}

var xxx_messageInfo_FUOTADeploymentDeviceListItem proto.InternalMessageInfo

func (m *FUOTADeploymentDeviceListItem) GetDevEui() string {
	if m != nil {
		return m.DevEui
	}
	return ""
}

func (m *FUOTADeploymentDeviceListItem) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *FUOTADeploymentDeviceListItem) GetState() FUOTADeploymentDeviceState {
	if m != nil {
		return m.State
	}
	return FUOTADeploymentDeviceState_PENDING
}

func (m *FUOTADeploymentDeviceListItem) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *FUOTADeploymentDeviceListItem) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *FUOTADeploymentDeviceListItem) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func init() {
	proto.RegisterEnum("appserver_serves_ui.FUOTADeploymentDeviceState", FUOTADeploymentDeviceState_name, FUOTADeploymentDeviceState_value)
	proto.RegisterType((*FUOTADeployment)(nil), "appserver_serves_ui.FUOTADeployment")
	proto.RegisterType((*FUOTADeploymentListItem)(nil), "appserver_serves_ui.FUOTADeploymentListItem")
	proto.RegisterType((*CreateFUOTADeploymentForDeviceRequest)(nil), "appserver_serves_ui.CreateFUOTADeploymentForDeviceRequest")
	proto.RegisterType((*CreateFUOTADeploymentForDeviceResponse)(nil), "appserver_serves_ui.CreateFUOTADeploymentForDeviceResponse")
	proto.RegisterType((*GetFUOTADeploymentRequest)(nil), "appserver_serves_ui.GetFUOTADeploymentRequest")
	proto.RegisterType((*GetFUOTADeploymentResponse)(nil), "appserver_serves_ui.GetFUOTADeploymentResponse")
	proto.RegisterType((*ListFUOTADeploymentRequest)(nil), "appserver_serves_ui.ListFUOTADeploymentRequest")
	proto.RegisterType((*ListFUOTADeploymentResponse)(nil), "appserver_serves_ui.ListFUOTADeploymentResponse")
	proto.RegisterType((*ListFUOTADeploymentDevicesRequest)(nil), "appserver_serves_ui.ListFUOTADeploymentDevicesRequest")
	proto.RegisterType((*GetFUOTADeploymentDeviceRequest)(nil), "appserver_serves_ui.GetFUOTADeploymentDeviceRequest")
	proto.RegisterType((*GetFUOTADeploymentDeviceResponse)(nil), "appserver_serves_ui.GetFUOTADeploymentDeviceResponse")
	proto.RegisterType((*ListFUOTADeploymentDevicesResponse)(nil), "appserver_serves_ui.ListFUOTADeploymentDevicesResponse")
	proto.RegisterType((*FUOTADeploymentDeviceListItem)(nil), "appserver_serves_ui.FUOTADeploymentDeviceListItem")
}

func init() { proto.RegisterFile("fuotaDeployment.proto", fileDescriptor_4f4a0a6fe690dc29) }

var fileDescriptor_4f4a0a6fe690dc29 = []byte{
	// 1053 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0x4d, 0x73, 0xe3, 0x44,
	0x13, 0x7e, 0x47, 0xfe, 0x7a, 0xdd, 0xde, 0x24, 0xce, 0x24, 0x9b, 0x28, 0xda, 0x8f, 0x18, 0x2d,
	0x0b, 0xae, 0x5d, 0xd6, 0xa6, 0xbc, 0xcb, 0x02, 0x0b, 0x45, 0x61, 0x62, 0xc7, 0x65, 0x8a, 0x4d,
	0x28, 0x39, 0x39, 0xab, 0xb4, 0xd6, 0xd8, 0x25, 0xca, 0x96, 0x84, 0x34, 0x4a, 0xe1, 0xda, 0xca,
	0x81, 0x8f, 0x0b, 0x4b, 0x71, 0xa0, 0xf8, 0x23, 0xdc, 0x39, 0x70, 0xe3, 0xc0, 0x95, 0x9f, 0x00,
	0x3f, 0x84, 0x9a, 0xd1, 0xc8, 0xb1, 0x65, 0x39, 0x91, 0xc3, 0x81, 0x93, 0x35, 0x3d, 0xdd, 0x3d,
	0x4f, 0x3f, 0xfd, 0x4c, 0x8f, 0xe1, 0xe6, 0x20, 0x70, 0xa8, 0xd1, 0x22, 0xee, 0xc8, 0x99, 0x8c,
	0x89, 0x4d, 0x6b, 0xae, 0xe7, 0x50, 0x07, 0x6f, 0x19, 0xae, 0xeb, 0x13, 0xef, 0x8c, 0x78, 0x3a,
	0xff, 0xf1, 0xf5, 0xc0, 0x52, 0x6e, 0x0f, 0x1d, 0x67, 0x38, 0x22, 0x75, 0xc3, 0xb5, 0xea, 0x86,
	0x6d, 0x3b, 0xd4, 0xa0, 0x96, 0x63, 0xfb, 0x61, 0x88, 0xb2, 0x47, 0xad, 0x31, 0xf1, 0xa9, 0x31,
	0x76, 0xeb, 0xd3, 0x2f, 0xb1, 0xb5, 0x6b, 0x06, 0x1e, 0xf7, 0xad, 0x47, 0x1f, 0x62, 0x63, 0x7b,
	0x1c, 0x8c, 0xa8, 0xd5, 0x37, 0x7c, 0xda, 0xf1, 0x9c, 0x40, 0xb8, 0xab, 0xbf, 0x64, 0x60, 0xe3,
	0xf0, 0xf4, 0xf8, 0xa4, 0x79, 0x01, 0x0b, 0xaf, 0x83, 0x64, 0x99, 0x32, 0xaa, 0xa0, 0x6a, 0x51,
	0x93, 0x2c, 0x13, 0x63, 0xc8, 0xda, 0xc6, 0x98, 0xc8, 0x12, 0xb7, 0xf0, 0x6f, 0x7c, 0x08, 0x30,
	0x64, 0x69, 0x74, 0x3a, 0x71, 0x89, 0x9c, 0xa9, 0xa0, 0xea, 0x7a, 0xe3, 0xcd, 0x5a, 0x42, 0x25,
	0xb5, 0xe7, 0x73, 0xc7, 0x9e, 0x4c, 0x5c, 0xa2, 0x15, 0x87, 0xd1, 0x27, 0x3b, 0xcb, 0xf4, 0xe4,
	0x6c, 0x05, 0x55, 0xd7, 0x34, 0xc9, 0xf4, 0xf0, 0x6d, 0x28, 0x0e, 0x3c, 0xf2, 0x65, 0x40, 0xec,
	0xfe, 0x44, 0xce, 0x71, 0xf3, 0x85, 0x01, 0xcb, 0x50, 0x70, 0x8d, 0xc9, 0xc8, 0x31, 0x4c, 0x39,
	0x5f, 0x41, 0xd5, 0x1b, 0x5a, 0xb4, 0xc4, 0x77, 0x01, 0x3c, 0x62, 0x06, 0xb6, 0x69, 0xb0, 0xc0,
	0x02, 0x0f, 0x9c, 0xb1, 0xe0, 0x87, 0xb0, 0x39, 0xad, 0x5f, 0x67, 0x9c, 0x39, 0x01, 0x95, 0xff,
	0xcf, 0xdd, 0xca, 0xd3, 0x8d, 0x93, 0xd0, 0x8e, 0x3f, 0x81, 0x8d, 0xc0, 0x9e, 0x77, 0x2d, 0x56,
	0x50, 0xb5, 0xd4, 0xd8, 0xab, 0x85, 0x6d, 0x09, 0xc9, 0x7b, 0x11, 0x0c, 0x6a, 0x2d, 0x41, 0xb2,
	0xb6, 0x2e, 0x22, 0xa2, 0x1c, 0xdb, 0x90, 0xf3, 0xa9, 0x41, 0x89, 0x0c, 0x9c, 0xb5, 0x70, 0xc1,
	0x32, 0xdb, 0xe4, 0x2b, 0xaa, 0xfb, 0x94, 0xb8, 0xba, 0x31, 0xa0, 0xc4, 0x93, 0x4b, 0x3c, 0xb3,
	0xb2, 0x90, 0xf9, 0x24, 0x6a, 0xac, 0xb6, 0xc6, 0x42, 0x7a, 0x94, 0xb8, 0x4d, 0x16, 0xa0, 0xfe,
	0x28, 0xc1, 0x6e, 0xac, 0x65, 0x9f, 0x59, 0x3e, 0xed, 0x52, 0x32, 0x5e, 0x68, 0xdd, 0xfb, 0x00,
	0x7d, 0x8f, 0x18, 0x94, 0x98, 0xba, 0x41, 0x79, 0x03, 0x2f, 0x3f, 0xaa, 0x28, 0xbc, 0x9b, 0x94,
	0x85, 0x06, 0xae, 0x19, 0x85, 0x66, 0xae, 0x0e, 0x15, 0xde, 0x4d, 0x3a, 0x15, 0x4c, 0x76, 0x46,
	0x30, 0x53, 0x3e, 0x72, 0x57, 0xf0, 0x91, 0x5f, 0x95, 0x8f, 0x9f, 0x10, 0xdc, 0x3f, 0xe0, 0xb0,
	0x63, 0xac, 0x1c, 0x3a, 0x5e, 0x8b, 0x9c, 0x59, 0x7d, 0xa2, 0x31, 0xfd, 0xf8, 0x14, 0xef, 0x42,
	0xc1, 0x24, 0x67, 0x3a, 0x09, 0x2c, 0x41, 0x51, 0xde, 0x24, 0x67, 0xed, 0xd3, 0x2e, 0x3e, 0x86,
	0x32, 0xbf, 0x9b, 0xba, 0x39, 0x0d, 0x16, 0x64, 0xbd, 0x9e, 0xa8, 0xe9, 0xd8, 0x41, 0xda, 0x46,
	0xec, 0x66, 0xab, 0xef, 0xc1, 0x1b, 0x57, 0x41, 0xf2, 0x5d, 0xc7, 0xf6, 0x49, 0xbc, 0x63, 0xea,
	0x43, 0xd8, 0xeb, 0x10, 0x1a, 0x3f, 0x40, 0x14, 0x10, 0x77, 0xfe, 0x0b, 0x81, 0x92, 0xe4, 0x2d,
	0x72, 0x27, 0x95, 0x85, 0xfe, 0x45, 0x59, 0xff, 0x8d, 0x9c, 0xd4, 0x57, 0x08, 0x14, 0xa6, 0xf0,
	0x25, 0xa4, 0x6c, 0x43, 0x6e, 0x64, 0x8d, 0xad, 0xb0, 0xb4, 0x8c, 0x16, 0x2e, 0xf0, 0x0e, 0xe4,
	0x9d, 0xc1, 0xc0, 0x27, 0x21, 0xcc, 0x8c, 0x26, 0x56, 0xf8, 0x3e, 0xac, 0x1b, 0xae, 0x3b, 0xb2,
	0xfa, 0xfc, 0xda, 0xea, 0x96, 0xc9, 0xb1, 0x64, 0xb4, 0xb5, 0x19, 0x6b, 0xb7, 0x35, 0x2b, 0x95,
	0xec, 0xac, 0x54, 0xd4, 0xef, 0x10, 0xdc, 0x4a, 0x04, 0x23, 0x38, 0xdf, 0x87, 0x12, 0x75, 0xa8,
	0x31, 0xd2, 0xfb, 0x4e, 0x60, 0x47, 0x98, 0x80, 0x9b, 0x0e, 0x98, 0x05, 0xb7, 0x20, 0xef, 0x11,
	0x3f, 0x18, 0x31, 0x60, 0x99, 0x6a, 0xa9, 0xf1, 0x56, 0x9a, 0x56, 0x44, 0x17, 0x5c, 0x13, 0xb1,
	0xea, 0xd7, 0x08, 0x5e, 0x4b, 0x80, 0x11, 0x8a, 0xcb, 0x8f, 0xa8, 0xa9, 0xc1, 0x56, 0x5c, 0x00,
	0xfa, 0x54, 0x40, 0x9b, 0xb1, 0xee, 0x76, 0x5b, 0x17, 0x54, 0x4a, 0xc9, 0x54, 0x66, 0x66, 0xa9,
	0x54, 0xbf, 0x80, 0xfd, 0x45, 0xf1, 0xcd, 0xdf, 0xb8, 0x55, 0x01, 0xcc, 0xd0, 0x2e, 0xcd, 0xd1,
	0xfe, 0x2d, 0x82, 0xca, 0xf2, 0xc3, 0x04, 0xf7, 0x3a, 0x6c, 0xce, 0x9c, 0x63, 0xf2, 0x4d, 0x21,
	0xf8, 0x46, 0x1a, 0x96, 0xc3, 0x74, 0x53, 0xae, 0xcb, 0x66, 0x6c, 0x87, 0x8d, 0x1a, 0xf5, 0x32,
	0xd6, 0xd3, 0x6a, 0xe0, 0xd3, 0x98, 0x06, 0xae, 0x83, 0x2e, 0x52, 0xc2, 0xaf, 0x12, 0xdc, 0xb9,
	0xd4, 0x73, 0xf9, 0xd8, 0xdb, 0x87, 0x52, 0x48, 0x92, 0x3e, 0xf3, 0xbe, 0x43, 0x68, 0x3a, 0x62,
	0x43, 0xbb, 0x1d, 0x0d, 0xed, 0xf0, 0x81, 0xaf, 0xa7, 0x87, 0xd9, 0x63, 0x61, 0xd1, 0x94, 0xbf,
	0x07, 0x6b, 0xc4, 0xf3, 0x1c, 0x4f, 0x1f, 0x13, 0xdf, 0x37, 0x86, 0xd1, 0xc3, 0x70, 0x83, 0x1b,
	0x9f, 0x87, 0xb6, 0xd8, 0x6c, 0xc9, 0x5d, 0x7f, 0xb6, 0xe4, 0x57, 0x98, 0x2d, 0x0f, 0x9a, 0xa0,
	0x2c, 0xc7, 0x8f, 0x4b, 0x50, 0xf8, 0xbc, 0x7d, 0xd4, 0xea, 0x1e, 0x75, 0xca, 0xff, 0x63, 0x8b,
	0xde, 0xe9, 0xc1, 0x41, 0xbb, 0xd7, 0x2b, 0x23, 0x5c, 0x84, 0x5c, 0x5b, 0xd3, 0x8e, 0xb5, 0xb2,
	0xd4, 0x78, 0x55, 0x80, 0x9d, 0x58, 0x8e, 0x1e, 0xf1, 0x58, 0x12, 0xfc, 0x1b, 0x82, 0x0d, 0xf1,
	0x0e, 0x44, 0x83, 0x1f, 0x3f, 0x4b, 0x24, 0x31, 0xd5, 0x03, 0xa6, 0x7c, 0x70, 0xad, 0xd8, 0x50,
	0x95, 0xea, 0xe3, 0x6f, 0xfe, 0xfc, 0xfb, 0x67, 0xe9, 0x91, 0x5a, 0xe5, 0x7f, 0x2a, 0xc3, 0x2e,
	0xfb, 0xf5, 0x97, 0x42, 0x1a, 0xe7, 0x75, 0x7e, 0x1b, 0x1f, 0x5d, 0x68, 0xde, 0x7f, 0x86, 0x1e,
	0xe0, 0x1f, 0x10, 0x64, 0x3a, 0x84, 0xe2, 0x5a, 0xe2, 0xc9, 0x4b, 0x5f, 0x2a, 0xa5, 0x9e, 0xda,
	0x5f, 0xa0, 0xbb, 0xc7, 0xd1, 0xdd, 0xc1, 0xb7, 0x38, 0xba, 0x05, 0x2c, 0xf5, 0x97, 0x96, 0x79,
	0x8e, 0xbf, 0x47, 0x90, 0x65, 0xb2, 0xc6, 0xc9, 0xe9, 0x97, 0x3f, 0x12, 0xca, 0xdb, 0xe9, 0x03,
	0x04, 0xa0, 0xbb, 0x1c, 0x90, 0x8c, 0x77, 0x92, 0x01, 0xe1, 0x3f, 0x10, 0x6c, 0x75, 0x08, 0x8d,
	0x0b, 0x07, 0x3f, 0x49, 0x59, 0xf9, 0x7c, 0x67, 0xdf, 0x59, 0x31, 0x4a, 0x80, 0x3c, 0xe4, 0x20,
	0x3f, 0xc6, 0x1f, 0x2d, 0x63, 0x2d, 0x61, 0xfa, 0x9e, 0x2f, 0xf6, 0x1e, 0xff, 0x8e, 0xe0, 0x26,
	0x23, 0x63, 0x61, 0xa6, 0xe1, 0xa7, 0x69, 0x89, 0x9b, 0x7f, 0x7a, 0x94, 0x77, 0x57, 0x8e, 0x13,
	0x25, 0x7d, 0xc8, 0x4b, 0x7a, 0x8a, 0x9f, 0x5c, 0xa7, 0xa4, 0x17, 0x79, 0x7e, 0xdd, 0x1f, 0xff,
	0x13, 0x00, 0x00, 0xff, 0xff, 0xca, 0x59, 0xbd, 0x69, 0x6c, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FUOTADeploymentServiceClient is the client API for FUOTADeploymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FUOTADeploymentServiceClient interface {
	// CreateForDevice creates a deployment for the given DevEUI.
	CreateForDevice(ctx context.Context, in *CreateFUOTADeploymentForDeviceRequest, opts ...grpc.CallOption) (*CreateFUOTADeploymentForDeviceResponse, error)
	// Get returns the fuota deployment for the given id.
	Get(ctx context.Context, in *GetFUOTADeploymentRequest, opts ...grpc.CallOption) (*GetFUOTADeploymentResponse, error)
	// List lists the fuota deployments.
	List(ctx context.Context, in *ListFUOTADeploymentRequest, opts ...grpc.CallOption) (*ListFUOTADeploymentResponse, error)
	// GetDeploymentDevice returns the deployment device.
	GetDeploymentDevice(ctx context.Context, in *GetFUOTADeploymentDeviceRequest, opts ...grpc.CallOption) (*GetFUOTADeploymentDeviceResponse, error)
	// ListDeploymentDevices lists the devices (and status) for the given fuota deployment ID.
	ListDeploymentDevices(ctx context.Context, in *ListFUOTADeploymentDevicesRequest, opts ...grpc.CallOption) (*ListFUOTADeploymentDevicesResponse, error)
}

type fUOTADeploymentServiceClient struct {
	cc *grpc.ClientConn
}

func NewFUOTADeploymentServiceClient(cc *grpc.ClientConn) FUOTADeploymentServiceClient {
	return &fUOTADeploymentServiceClient{cc}
}

func (c *fUOTADeploymentServiceClient) CreateForDevice(ctx context.Context, in *CreateFUOTADeploymentForDeviceRequest, opts ...grpc.CallOption) (*CreateFUOTADeploymentForDeviceResponse, error) {
	out := new(CreateFUOTADeploymentForDeviceResponse)
	err := c.cc.Invoke(ctx, "/appserver_serves_ui.FUOTADeploymentService/CreateForDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fUOTADeploymentServiceClient) Get(ctx context.Context, in *GetFUOTADeploymentRequest, opts ...grpc.CallOption) (*GetFUOTADeploymentResponse, error) {
	out := new(GetFUOTADeploymentResponse)
	err := c.cc.Invoke(ctx, "/appserver_serves_ui.FUOTADeploymentService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fUOTADeploymentServiceClient) List(ctx context.Context, in *ListFUOTADeploymentRequest, opts ...grpc.CallOption) (*ListFUOTADeploymentResponse, error) {
	out := new(ListFUOTADeploymentResponse)
	err := c.cc.Invoke(ctx, "/appserver_serves_ui.FUOTADeploymentService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fUOTADeploymentServiceClient) GetDeploymentDevice(ctx context.Context, in *GetFUOTADeploymentDeviceRequest, opts ...grpc.CallOption) (*GetFUOTADeploymentDeviceResponse, error) {
	out := new(GetFUOTADeploymentDeviceResponse)
	err := c.cc.Invoke(ctx, "/appserver_serves_ui.FUOTADeploymentService/GetDeploymentDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fUOTADeploymentServiceClient) ListDeploymentDevices(ctx context.Context, in *ListFUOTADeploymentDevicesRequest, opts ...grpc.CallOption) (*ListFUOTADeploymentDevicesResponse, error) {
	out := new(ListFUOTADeploymentDevicesResponse)
	err := c.cc.Invoke(ctx, "/appserver_serves_ui.FUOTADeploymentService/ListDeploymentDevices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FUOTADeploymentServiceServer is the server API for FUOTADeploymentService service.
type FUOTADeploymentServiceServer interface {
	// CreateForDevice creates a deployment for the given DevEUI.
	CreateForDevice(context.Context, *CreateFUOTADeploymentForDeviceRequest) (*CreateFUOTADeploymentForDeviceResponse, error)
	// Get returns the fuota deployment for the given id.
	Get(context.Context, *GetFUOTADeploymentRequest) (*GetFUOTADeploymentResponse, error)
	// List lists the fuota deployments.
	List(context.Context, *ListFUOTADeploymentRequest) (*ListFUOTADeploymentResponse, error)
	// GetDeploymentDevice returns the deployment device.
	GetDeploymentDevice(context.Context, *GetFUOTADeploymentDeviceRequest) (*GetFUOTADeploymentDeviceResponse, error)
	// ListDeploymentDevices lists the devices (and status) for the given fuota deployment ID.
	ListDeploymentDevices(context.Context, *ListFUOTADeploymentDevicesRequest) (*ListFUOTADeploymentDevicesResponse, error)
}

// UnimplementedFUOTADeploymentServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFUOTADeploymentServiceServer struct {
}

func (*UnimplementedFUOTADeploymentServiceServer) CreateForDevice(ctx context.Context, req *CreateFUOTADeploymentForDeviceRequest) (*CreateFUOTADeploymentForDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateForDevice not implemented")
}
func (*UnimplementedFUOTADeploymentServiceServer) Get(ctx context.Context, req *GetFUOTADeploymentRequest) (*GetFUOTADeploymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedFUOTADeploymentServiceServer) List(ctx context.Context, req *ListFUOTADeploymentRequest) (*ListFUOTADeploymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedFUOTADeploymentServiceServer) GetDeploymentDevice(ctx context.Context, req *GetFUOTADeploymentDeviceRequest) (*GetFUOTADeploymentDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeploymentDevice not implemented")
}
func (*UnimplementedFUOTADeploymentServiceServer) ListDeploymentDevices(ctx context.Context, req *ListFUOTADeploymentDevicesRequest) (*ListFUOTADeploymentDevicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDeploymentDevices not implemented")
}

func RegisterFUOTADeploymentServiceServer(s *grpc.Server, srv FUOTADeploymentServiceServer) {
	s.RegisterService(&_FUOTADeploymentService_serviceDesc, srv)
}

func _FUOTADeploymentService_CreateForDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFUOTADeploymentForDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FUOTADeploymentServiceServer).CreateForDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appserver_serves_ui.FUOTADeploymentService/CreateForDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FUOTADeploymentServiceServer).CreateForDevice(ctx, req.(*CreateFUOTADeploymentForDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FUOTADeploymentService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFUOTADeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FUOTADeploymentServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appserver_serves_ui.FUOTADeploymentService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FUOTADeploymentServiceServer).Get(ctx, req.(*GetFUOTADeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FUOTADeploymentService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFUOTADeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FUOTADeploymentServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appserver_serves_ui.FUOTADeploymentService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FUOTADeploymentServiceServer).List(ctx, req.(*ListFUOTADeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FUOTADeploymentService_GetDeploymentDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFUOTADeploymentDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FUOTADeploymentServiceServer).GetDeploymentDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appserver_serves_ui.FUOTADeploymentService/GetDeploymentDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FUOTADeploymentServiceServer).GetDeploymentDevice(ctx, req.(*GetFUOTADeploymentDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FUOTADeploymentService_ListDeploymentDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFUOTADeploymentDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FUOTADeploymentServiceServer).ListDeploymentDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appserver_serves_ui.FUOTADeploymentService/ListDeploymentDevices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FUOTADeploymentServiceServer).ListDeploymentDevices(ctx, req.(*ListFUOTADeploymentDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FUOTADeploymentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "appserver_serves_ui.FUOTADeploymentService",
	HandlerType: (*FUOTADeploymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateForDevice",
			Handler:    _FUOTADeploymentService_CreateForDevice_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _FUOTADeploymentService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _FUOTADeploymentService_List_Handler,
		},
		{
			MethodName: "GetDeploymentDevice",
			Handler:    _FUOTADeploymentService_GetDeploymentDevice_Handler,
		},
		{
			MethodName: "ListDeploymentDevices",
			Handler:    _FUOTADeploymentService_ListDeploymentDevices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fuotaDeployment.proto",
}
