#!/bin/sh

echo "running script: sync_env_variables "

PROJECT_PATH=$(dirname $0)/..
ENV_CONFIGURATION=$PROJECT_PATH/ui/.env.production

if [ -f $ENV_CONFIGURATION ]; then
  echo "### assign paremeter 'REACT_APP_MXPROTOCOL_SERVER' in" $ENV_CONFIGURATION "with" $MXPROTOCOL_SERVER
  sed -i.bak 's,REACT_APP_MXPROTOCOL_SERVER=.*,REACT_APP_MXPROTOCOL_SERVER="'$MXPROTOCOL_SERVER'",' $ENV_CONFIGURATION
fi
