// Code generated by protoc-gen-go. DO NOT EDIT.
// source: inner_device.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddDeviceInM2MServerRequest struct {
	OrgId                int64            `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	DevProfile           []*DeviceProfile `protobuf:"bytes,2,rep,name=dev_profile,json=devProfile,proto3" json:"dev_profile,omitempty"`
	MacAddress           string           `protobuf:"bytes,3,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AddDeviceInM2MServerRequest) Reset()         { *m = AddDeviceInM2MServerRequest{} }
func (m *AddDeviceInM2MServerRequest) String() string { return proto.CompactTextString(m) }
func (*AddDeviceInM2MServerRequest) ProtoMessage()    {}
func (*AddDeviceInM2MServerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_06b99fe8ee14f928, []int{0}
}

func (m *AddDeviceInM2MServerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddDeviceInM2MServerRequest.Unmarshal(m, b)
}
func (m *AddDeviceInM2MServerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddDeviceInM2MServerRequest.Marshal(b, m, deterministic)
}
func (m *AddDeviceInM2MServerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddDeviceInM2MServerRequest.Merge(m, src)
}
func (m *AddDeviceInM2MServerRequest) XXX_Size() int {
	return xxx_messageInfo_AddDeviceInM2MServerRequest.Size(m)
}
func (m *AddDeviceInM2MServerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddDeviceInM2MServerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddDeviceInM2MServerRequest proto.InternalMessageInfo

func (m *AddDeviceInM2MServerRequest) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *AddDeviceInM2MServerRequest) GetDevProfile() []*DeviceProfile {
	if m != nil {
		return m.DevProfile
	}
	return nil
}

func (m *AddDeviceInM2MServerRequest) GetMacAddress() string {
	if m != nil {
		return m.MacAddress
	}
	return ""
}

type AddDeviceInM2MServerResponse struct {
	DevId                int64            `protobuf:"varint,1,opt,name=dev_id,json=devId,proto3" json:"dev_id,omitempty"`
	UserProfile          *ProfileResponse `protobuf:"bytes,2,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AddDeviceInM2MServerResponse) Reset()         { *m = AddDeviceInM2MServerResponse{} }
func (m *AddDeviceInM2MServerResponse) String() string { return proto.CompactTextString(m) }
func (*AddDeviceInM2MServerResponse) ProtoMessage()    {}
func (*AddDeviceInM2MServerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_06b99fe8ee14f928, []int{1}
}

func (m *AddDeviceInM2MServerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddDeviceInM2MServerResponse.Unmarshal(m, b)
}
func (m *AddDeviceInM2MServerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddDeviceInM2MServerResponse.Marshal(b, m, deterministic)
}
func (m *AddDeviceInM2MServerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddDeviceInM2MServerResponse.Merge(m, src)
}
func (m *AddDeviceInM2MServerResponse) XXX_Size() int {
	return xxx_messageInfo_AddDeviceInM2MServerResponse.Size(m)
}
func (m *AddDeviceInM2MServerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddDeviceInM2MServerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddDeviceInM2MServerResponse proto.InternalMessageInfo

func (m *AddDeviceInM2MServerResponse) GetDevId() int64 {
	if m != nil {
		return m.DevId
	}
	return 0
}

func (m *AddDeviceInM2MServerResponse) GetUserProfile() *ProfileResponse {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

type DeleteDeviceInM2MServerRequest struct {
	OrgId                int64    `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	MacAddress           string   `protobuf:"bytes,2,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDeviceInM2MServerRequest) Reset()         { *m = DeleteDeviceInM2MServerRequest{} }
func (m *DeleteDeviceInM2MServerRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteDeviceInM2MServerRequest) ProtoMessage()    {}
func (*DeleteDeviceInM2MServerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_06b99fe8ee14f928, []int{2}
}

func (m *DeleteDeviceInM2MServerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDeviceInM2MServerRequest.Unmarshal(m, b)
}
func (m *DeleteDeviceInM2MServerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDeviceInM2MServerRequest.Marshal(b, m, deterministic)
}
func (m *DeleteDeviceInM2MServerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDeviceInM2MServerRequest.Merge(m, src)
}
func (m *DeleteDeviceInM2MServerRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteDeviceInM2MServerRequest.Size(m)
}
func (m *DeleteDeviceInM2MServerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDeviceInM2MServerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDeviceInM2MServerRequest proto.InternalMessageInfo

func (m *DeleteDeviceInM2MServerRequest) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *DeleteDeviceInM2MServerRequest) GetMacAddress() string {
	if m != nil {
		return m.MacAddress
	}
	return ""
}

type DeleteDeviceInM2MServerResponse struct {
	Status               bool             `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	UserProfile          *ProfileResponse `protobuf:"bytes,2,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DeleteDeviceInM2MServerResponse) Reset()         { *m = DeleteDeviceInM2MServerResponse{} }
func (m *DeleteDeviceInM2MServerResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteDeviceInM2MServerResponse) ProtoMessage()    {}
func (*DeleteDeviceInM2MServerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_06b99fe8ee14f928, []int{3}
}

func (m *DeleteDeviceInM2MServerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDeviceInM2MServerResponse.Unmarshal(m, b)
}
func (m *DeleteDeviceInM2MServerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDeviceInM2MServerResponse.Marshal(b, m, deterministic)
}
func (m *DeleteDeviceInM2MServerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDeviceInM2MServerResponse.Merge(m, src)
}
func (m *DeleteDeviceInM2MServerResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteDeviceInM2MServerResponse.Size(m)
}
func (m *DeleteDeviceInM2MServerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDeviceInM2MServerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDeviceInM2MServerResponse proto.InternalMessageInfo

func (m *DeleteDeviceInM2MServerResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *DeleteDeviceInM2MServerResponse) GetUserProfile() *ProfileResponse {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

func init() {
	proto.RegisterType((*AddDeviceInM2MServerRequest)(nil), "api.AddDeviceInM2MServerRequest")
	proto.RegisterType((*AddDeviceInM2MServerResponse)(nil), "api.AddDeviceInM2MServerResponse")
	proto.RegisterType((*DeleteDeviceInM2MServerRequest)(nil), "api.DeleteDeviceInM2MServerRequest")
	proto.RegisterType((*DeleteDeviceInM2MServerResponse)(nil), "api.DeleteDeviceInM2MServerResponse")
}

func init() { proto.RegisterFile("inner_device.proto", fileDescriptor_06b99fe8ee14f928) }

var fileDescriptor_06b99fe8ee14f928 = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xc1, 0x4a, 0xf3, 0x40,
	0x14, 0x85, 0x99, 0x86, 0xbf, 0xfc, 0xde, 0x54, 0x90, 0xa1, 0x6a, 0x89, 0x62, 0x63, 0x75, 0x91,
	0x55, 0x17, 0xe9, 0xc2, 0x75, 0xa1, 0x9b, 0x2e, 0x02, 0x32, 0x6e, 0x04, 0x17, 0x61, 0xcc, 0xbd,
	0x96, 0x81, 0x36, 0x13, 0x67, 0xd2, 0x3c, 0x84, 0xef, 0xe7, 0xfb, 0x48, 0x92, 0x11, 0x8b, 0xb6,
	0x01, 0xdd, 0x65, 0x6e, 0x0e, 0xe7, 0x9c, 0x6f, 0xe6, 0x02, 0x57, 0x79, 0x4e, 0x26, 0x45, 0xaa,
	0x54, 0x46, 0xd3, 0xc2, 0xe8, 0x52, 0x73, 0x4f, 0x16, 0x2a, 0x18, 0xec, 0x8e, 0x82, 0xe3, 0xc2,
	0xe8, 0x17, 0xb5, 0x76, 0xc7, 0xc9, 0x1b, 0x83, 0x8b, 0x39, 0xe2, 0xa2, 0x91, 0x2c, 0xf3, 0x24,
	0x4e, 0x1e, 0xc8, 0x54, 0x64, 0x04, 0xbd, 0x6e, 0xc9, 0x96, 0xfc, 0x14, 0xfa, 0xda, 0xac, 0x52,
	0x85, 0x23, 0x16, 0xb2, 0xc8, 0x13, 0xff, 0xb4, 0x59, 0x2d, 0x91, 0xcf, 0xc0, 0x47, 0xaa, 0x52,
	0xe7, 0x35, 0xea, 0x85, 0x5e, 0xe4, 0xc7, 0x7c, 0x2a, 0x0b, 0x35, 0x6d, 0xad, 0xee, 0xdb, 0x3f,
	0x02, 0x90, 0x2a, 0xf7, 0xcd, 0xc7, 0xe0, 0x6f, 0x64, 0x96, 0x4a, 0x44, 0x43, 0xd6, 0x8e, 0xbc,
	0x90, 0x45, 0x47, 0x02, 0x36, 0x32, 0x9b, 0xb7, 0x93, 0x49, 0x0e, 0x97, 0xfb, 0xbb, 0xd8, 0x42,
	0xe7, 0x96, 0xea, 0x32, 0x75, 0xea, 0x57, 0x19, 0xa4, 0x6a, 0x89, 0xfc, 0x0e, 0x06, 0x5b, 0x4b,
	0x66, 0xa7, 0x0d, 0x8b, 0xfc, 0x78, 0xd8, 0xb4, 0xf9, 0xec, 0xe1, 0x2c, 0x84, 0x5f, 0x2b, 0xdd,
	0x70, 0xf2, 0x08, 0x57, 0x0b, 0x5a, 0x53, 0x49, 0xbf, 0xc5, 0xff, 0x46, 0xd2, 0xfb, 0x41, 0x62,
	0x60, 0x7c, 0xd0, 0xd9, 0xc1, 0x9c, 0x41, 0xdf, 0x96, 0xb2, 0xdc, 0xda, 0xc6, 0xfa, 0xbf, 0x70,
	0xa7, 0x3f, 0xd3, 0xc4, 0xef, 0x0c, 0x4e, 0x92, 0x38, 0x69, 0x13, 0xeb, 0x30, 0x95, 0x11, 0x7f,
	0x82, 0xe1, 0xbe, 0x2b, 0xe5, 0x61, 0xe3, 0xd7, 0xf1, 0xf2, 0xc1, 0x75, 0x87, 0xc2, 0x21, 0x20,
	0x9c, 0x1f, 0xa0, 0xe4, 0x37, 0x6e, 0x17, 0xba, 0x6e, 0x37, 0xb8, 0xed, 0x16, 0xb5, 0x29, 0xcf,
	0xfd, 0x66, 0x53, 0x67, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3e, 0xa3, 0xe3, 0xb3, 0xe1, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// M2MDeviceServiceClient is the client API for M2MDeviceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type M2MDeviceServiceClient interface {
	AddDeviceInM2MServer(ctx context.Context, in *AddDeviceInM2MServerRequest, opts ...grpc.CallOption) (*AddDeviceInM2MServerResponse, error)
	DeleteDeviceInM2MServer(ctx context.Context, in *DeleteDeviceInM2MServerRequest, opts ...grpc.CallOption) (*DeleteDeviceInM2MServerResponse, error)
}

type m2MDeviceServiceClient struct {
	cc *grpc.ClientConn
}

func NewM2MDeviceServiceClient(cc *grpc.ClientConn) M2MDeviceServiceClient {
	return &m2MDeviceServiceClient{cc}
}

func (c *m2MDeviceServiceClient) AddDeviceInM2MServer(ctx context.Context, in *AddDeviceInM2MServerRequest, opts ...grpc.CallOption) (*AddDeviceInM2MServerResponse, error) {
	out := new(AddDeviceInM2MServerResponse)
	err := c.cc.Invoke(ctx, "/api.M2MDeviceService/AddDeviceInM2MServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *m2MDeviceServiceClient) DeleteDeviceInM2MServer(ctx context.Context, in *DeleteDeviceInM2MServerRequest, opts ...grpc.CallOption) (*DeleteDeviceInM2MServerResponse, error) {
	out := new(DeleteDeviceInM2MServerResponse)
	err := c.cc.Invoke(ctx, "/api.M2MDeviceService/DeleteDeviceInM2MServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// M2MDeviceServiceServer is the server API for M2MDeviceService service.
type M2MDeviceServiceServer interface {
	AddDeviceInM2MServer(context.Context, *AddDeviceInM2MServerRequest) (*AddDeviceInM2MServerResponse, error)
	DeleteDeviceInM2MServer(context.Context, *DeleteDeviceInM2MServerRequest) (*DeleteDeviceInM2MServerResponse, error)
}

// UnimplementedM2MDeviceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedM2MDeviceServiceServer struct {
}

func (*UnimplementedM2MDeviceServiceServer) AddDeviceInM2MServer(ctx context.Context, req *AddDeviceInM2MServerRequest) (*AddDeviceInM2MServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDeviceInM2MServer not implemented")
}
func (*UnimplementedM2MDeviceServiceServer) DeleteDeviceInM2MServer(ctx context.Context, req *DeleteDeviceInM2MServerRequest) (*DeleteDeviceInM2MServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDeviceInM2MServer not implemented")
}

func RegisterM2MDeviceServiceServer(s *grpc.Server, srv M2MDeviceServiceServer) {
	s.RegisterService(&_M2MDeviceService_serviceDesc, srv)
}

func _M2MDeviceService_AddDeviceInM2MServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDeviceInM2MServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(M2MDeviceServiceServer).AddDeviceInM2MServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.M2MDeviceService/AddDeviceInM2MServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(M2MDeviceServiceServer).AddDeviceInM2MServer(ctx, req.(*AddDeviceInM2MServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _M2MDeviceService_DeleteDeviceInM2MServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDeviceInM2MServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(M2MDeviceServiceServer).DeleteDeviceInM2MServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.M2MDeviceService/DeleteDeviceInM2MServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(M2MDeviceServiceServer).DeleteDeviceInM2MServer(ctx, req.(*DeleteDeviceInM2MServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _M2MDeviceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.M2MDeviceService",
	HandlerType: (*M2MDeviceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddDeviceInM2MServer",
			Handler:    _M2MDeviceService_AddDeviceInM2MServer_Handler,
		},
		{
			MethodName: "DeleteDeviceInM2MServer",
			Handler:    _M2MDeviceService_DeleteDeviceInM2MServer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inner_device.proto",
}
