// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.2
// source: shopify_integration.proto

package appserver_serves_ui

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetOrdersByUserIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetOrdersByUserIDRequest) Reset() {
	*x = GetOrdersByUserIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shopify_integration_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrdersByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersByUserIDRequest) ProtoMessage() {}

func (x *GetOrdersByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopify_integration_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersByUserIDRequest.ProtoReflect.Descriptor instead.
func (*GetOrdersByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_shopify_integration_proto_rawDescGZIP(), []int{0}
}

func (x *GetOrdersByUserIDRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ShopifySuccessfulOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopifyAccount string               `protobuf:"bytes,1,opt,name=shopify_account,json=shopifyAccount,proto3" json:"shopify_account,omitempty"`
	OrderId        string               `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CreatedAt      *timestamp.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Amount         int64                `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	ProductId      string               `protobuf:"bytes,5,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	BonusStatus    string               `protobuf:"bytes,6,opt,name=bonus_status,json=bonusStatus,proto3" json:"bonus_status,omitempty"`
}

func (x *ShopifySuccessfulOrder) Reset() {
	*x = ShopifySuccessfulOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shopify_integration_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShopifySuccessfulOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopifySuccessfulOrder) ProtoMessage() {}

func (x *ShopifySuccessfulOrder) ProtoReflect() protoreflect.Message {
	mi := &file_shopify_integration_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopifySuccessfulOrder.ProtoReflect.Descriptor instead.
func (*ShopifySuccessfulOrder) Descriptor() ([]byte, []int) {
	return file_shopify_integration_proto_rawDescGZIP(), []int{1}
}

func (x *ShopifySuccessfulOrder) GetShopifyAccount() string {
	if x != nil {
		return x.ShopifyAccount
	}
	return ""
}

func (x *ShopifySuccessfulOrder) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ShopifySuccessfulOrder) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ShopifySuccessfulOrder) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ShopifySuccessfulOrder) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ShopifySuccessfulOrder) GetBonusStatus() string {
	if x != nil {
		return x.BonusStatus
	}
	return ""
}

type GetOrdersByUserIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SuccessfulOrders []*ShopifySuccessfulOrder `protobuf:"bytes,1,rep,name=successful_orders,json=successfulOrders,proto3" json:"successful_orders,omitempty"`
}

func (x *GetOrdersByUserIDResponse) Reset() {
	*x = GetOrdersByUserIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shopify_integration_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrdersByUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersByUserIDResponse) ProtoMessage() {}

func (x *GetOrdersByUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shopify_integration_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersByUserIDResponse.ProtoReflect.Descriptor instead.
func (*GetOrdersByUserIDResponse) Descriptor() ([]byte, []int) {
	return file_shopify_integration_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrdersByUserIDResponse) GetSuccessfulOrders() []*ShopifySuccessfulOrder {
	if x != nil {
		return x.SuccessfulOrders
	}
	return nil
}

var File_shopify_integration_proto protoreflect.FileDescriptor

var file_shopify_integration_proto_rawDesc = []byte{
	0x0a, 0x19, 0x73, 0x68, 0x6f, 0x70, 0x69, 0x66, 0x79, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x61, 0x70, 0x70,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x73, 0x5f, 0x75, 0x69,
	0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x33, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x42, 0x79, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x22, 0xf1, 0x01, 0x0a, 0x16, 0x53, 0x68, 0x6f, 0x70, 0x69, 0x66, 0x79,
	0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12,
	0x27, 0x0a, 0x0f, 0x73, 0x68, 0x6f, 0x70, 0x69, 0x66, 0x79, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x68, 0x6f, 0x70, 0x69, 0x66,
	0x79, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x62, 0x6f, 0x6e,
	0x75, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x75, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x73, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x11, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x66, 0x75, 0x6c, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x2b, 0x2e, 0x61, 0x70, 0x70, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x73, 0x5f, 0x75, 0x69, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x69, 0x66, 0x79, 0x53, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x10, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x32,
	0xc0, 0x01, 0x0a, 0x12, 0x53, 0x68, 0x6f, 0x70, 0x69, 0x66, 0x79, 0x49, 0x6e, 0x74, 0x65, 0x67,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0xa9, 0x01, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x73, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x2d, 0x2e, 0x61,
	0x70, 0x70, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x73, 0x5f,
	0x75, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x42, 0x79, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x61, 0x70,
	0x70, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x73, 0x5f, 0x75,
	0x69, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x42, 0x79, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x35, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x2f, 0x12, 0x2d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x68, 0x6f, 0x70, 0x69, 0x66,
	0x79, 0x2d, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x73, 0x2f, 0x67, 0x65, 0x74, 0x2f, 0x7b, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x7d, 0x42, 0x58, 0x5a, 0x56, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6d, 0x78, 0x63, 0x2d, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f,
	0x6c, 0x70, 0x77, 0x61, 0x6e, 0x2d, 0x61, 0x70, 0x70, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2d, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x73, 0x2d, 0x75, 0x69, 0x3b, 0x61, 0x70, 0x70, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x73, 0x5f, 0x75, 0x69, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shopify_integration_proto_rawDescOnce sync.Once
	file_shopify_integration_proto_rawDescData = file_shopify_integration_proto_rawDesc
)

func file_shopify_integration_proto_rawDescGZIP() []byte {
	file_shopify_integration_proto_rawDescOnce.Do(func() {
		file_shopify_integration_proto_rawDescData = protoimpl.X.CompressGZIP(file_shopify_integration_proto_rawDescData)
	})
	return file_shopify_integration_proto_rawDescData
}

var file_shopify_integration_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_shopify_integration_proto_goTypes = []interface{}{
	(*GetOrdersByUserIDRequest)(nil),  // 0: appserver_serves_ui.GetOrdersByUserIDRequest
	(*ShopifySuccessfulOrder)(nil),    // 1: appserver_serves_ui.ShopifySuccessfulOrder
	(*GetOrdersByUserIDResponse)(nil), // 2: appserver_serves_ui.GetOrdersByUserIDResponse
	(*timestamp.Timestamp)(nil),       // 3: google.protobuf.Timestamp
}
var file_shopify_integration_proto_depIdxs = []int32{
	3, // 0: appserver_serves_ui.ShopifySuccessfulOrder.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: appserver_serves_ui.GetOrdersByUserIDResponse.successful_orders:type_name -> appserver_serves_ui.ShopifySuccessfulOrder
	0, // 2: appserver_serves_ui.ShopifyIntegration.GetOrdersByUserID:input_type -> appserver_serves_ui.GetOrdersByUserIDRequest
	2, // 3: appserver_serves_ui.ShopifyIntegration.GetOrdersByUserID:output_type -> appserver_serves_ui.GetOrdersByUserIDResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shopify_integration_proto_init() }
func file_shopify_integration_proto_init() {
	if File_shopify_integration_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shopify_integration_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrdersByUserIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shopify_integration_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShopifySuccessfulOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shopify_integration_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrdersByUserIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shopify_integration_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shopify_integration_proto_goTypes,
		DependencyIndexes: file_shopify_integration_proto_depIdxs,
		MessageInfos:      file_shopify_integration_proto_msgTypes,
	}.Build()
	File_shopify_integration_proto = out.File
	file_shopify_integration_proto_rawDesc = nil
	file_shopify_integration_proto_goTypes = nil
	file_shopify_integration_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ShopifyIntegrationClient is the client API for ShopifyIntegration service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShopifyIntegrationClient interface {
	// GetOrdersByUserID returns a list of shopify orders filtered by given user id
	GetOrdersByUserID(ctx context.Context, in *GetOrdersByUserIDRequest, opts ...grpc.CallOption) (*GetOrdersByUserIDResponse, error)
}

type shopifyIntegrationClient struct {
	cc grpc.ClientConnInterface
}

func NewShopifyIntegrationClient(cc grpc.ClientConnInterface) ShopifyIntegrationClient {
	return &shopifyIntegrationClient{cc}
}

func (c *shopifyIntegrationClient) GetOrdersByUserID(ctx context.Context, in *GetOrdersByUserIDRequest, opts ...grpc.CallOption) (*GetOrdersByUserIDResponse, error) {
	out := new(GetOrdersByUserIDResponse)
	err := c.cc.Invoke(ctx, "/appserver_serves_ui.ShopifyIntegration/GetOrdersByUserID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShopifyIntegrationServer is the server API for ShopifyIntegration service.
type ShopifyIntegrationServer interface {
	// GetOrdersByUserID returns a list of shopify orders filtered by given user id
	GetOrdersByUserID(context.Context, *GetOrdersByUserIDRequest) (*GetOrdersByUserIDResponse, error)
}

// UnimplementedShopifyIntegrationServer can be embedded to have forward compatible implementations.
type UnimplementedShopifyIntegrationServer struct {
}

func (*UnimplementedShopifyIntegrationServer) GetOrdersByUserID(context.Context, *GetOrdersByUserIDRequest) (*GetOrdersByUserIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrdersByUserID not implemented")
}

func RegisterShopifyIntegrationServer(s *grpc.Server, srv ShopifyIntegrationServer) {
	s.RegisterService(&_ShopifyIntegration_serviceDesc, srv)
}

func _ShopifyIntegration_GetOrdersByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrdersByUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopifyIntegrationServer).GetOrdersByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appserver_serves_ui.ShopifyIntegration/GetOrdersByUserID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopifyIntegrationServer).GetOrdersByUserID(ctx, req.(*GetOrdersByUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShopifyIntegration_serviceDesc = grpc.ServiceDesc{
	ServiceName: "appserver_serves_ui.ShopifyIntegration",
	HandlerType: (*ShopifyIntegrationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrdersByUserID",
			Handler:    _ShopifyIntegration_GetOrdersByUserID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shopify_integration.proto",
}
