// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wallet.proto

package appserver_serves_ui

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetWalletBalanceRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrgId                int64    `protobuf:"varint,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Currency             string   `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWalletBalanceRequest) Reset()         { *m = GetWalletBalanceRequest{} }
func (m *GetWalletBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*GetWalletBalanceRequest) ProtoMessage()    {}
func (*GetWalletBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{0}
}

func (m *GetWalletBalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWalletBalanceRequest.Unmarshal(m, b)
}
func (m *GetWalletBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWalletBalanceRequest.Marshal(b, m, deterministic)
}
func (m *GetWalletBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWalletBalanceRequest.Merge(m, src)
}
func (m *GetWalletBalanceRequest) XXX_Size() int {
	return xxx_messageInfo_GetWalletBalanceRequest.Size(m)
}
func (m *GetWalletBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWalletBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetWalletBalanceRequest proto.InternalMessageInfo

func (m *GetWalletBalanceRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetWalletBalanceRequest) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *GetWalletBalanceRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

type GetWalletBalanceResponse struct {
	Balance              string           `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	UserProfile          *ProfileResponse `protobuf:"bytes,2,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetWalletBalanceResponse) Reset()         { *m = GetWalletBalanceResponse{} }
func (m *GetWalletBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*GetWalletBalanceResponse) ProtoMessage()    {}
func (*GetWalletBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{1}
}

func (m *GetWalletBalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWalletBalanceResponse.Unmarshal(m, b)
}
func (m *GetWalletBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWalletBalanceResponse.Marshal(b, m, deterministic)
}
func (m *GetWalletBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWalletBalanceResponse.Merge(m, src)
}
func (m *GetWalletBalanceResponse) XXX_Size() int {
	return xxx_messageInfo_GetWalletBalanceResponse.Size(m)
}
func (m *GetWalletBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWalletBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetWalletBalanceResponse proto.InternalMessageInfo

func (m *GetWalletBalanceResponse) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *GetWalletBalanceResponse) GetUserProfile() *ProfileResponse {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

type GetWalletMiningIncomeRequest struct {
	OrgId                int64                `protobuf:"varint,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Currency             string               `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	From                 *timestamp.Timestamp `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	Till                 *timestamp.Timestamp `protobuf:"bytes,5,opt,name=till,proto3" json:"till,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetWalletMiningIncomeRequest) Reset()         { *m = GetWalletMiningIncomeRequest{} }
func (m *GetWalletMiningIncomeRequest) String() string { return proto.CompactTextString(m) }
func (*GetWalletMiningIncomeRequest) ProtoMessage()    {}
func (*GetWalletMiningIncomeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{2}
}

func (m *GetWalletMiningIncomeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWalletMiningIncomeRequest.Unmarshal(m, b)
}
func (m *GetWalletMiningIncomeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWalletMiningIncomeRequest.Marshal(b, m, deterministic)
}
func (m *GetWalletMiningIncomeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWalletMiningIncomeRequest.Merge(m, src)
}
func (m *GetWalletMiningIncomeRequest) XXX_Size() int {
	return xxx_messageInfo_GetWalletMiningIncomeRequest.Size(m)
}
func (m *GetWalletMiningIncomeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWalletMiningIncomeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetWalletMiningIncomeRequest proto.InternalMessageInfo

func (m *GetWalletMiningIncomeRequest) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *GetWalletMiningIncomeRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *GetWalletMiningIncomeRequest) GetFrom() *timestamp.Timestamp {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *GetWalletMiningIncomeRequest) GetTill() *timestamp.Timestamp {
	if m != nil {
		return m.Till
	}
	return nil
}

type GetWalletMiningIncomeResponse struct {
	MiningIncome         string           `protobuf:"bytes,1,opt,name=mining_income,json=miningIncome,proto3" json:"mining_income,omitempty"`
	UserProfile          *ProfileResponse `protobuf:"bytes,2,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetWalletMiningIncomeResponse) Reset()         { *m = GetWalletMiningIncomeResponse{} }
func (m *GetWalletMiningIncomeResponse) String() string { return proto.CompactTextString(m) }
func (*GetWalletMiningIncomeResponse) ProtoMessage()    {}
func (*GetWalletMiningIncomeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{3}
}

func (m *GetWalletMiningIncomeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWalletMiningIncomeResponse.Unmarshal(m, b)
}
func (m *GetWalletMiningIncomeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWalletMiningIncomeResponse.Marshal(b, m, deterministic)
}
func (m *GetWalletMiningIncomeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWalletMiningIncomeResponse.Merge(m, src)
}
func (m *GetWalletMiningIncomeResponse) XXX_Size() int {
	return xxx_messageInfo_GetWalletMiningIncomeResponse.Size(m)
}
func (m *GetWalletMiningIncomeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWalletMiningIncomeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetWalletMiningIncomeResponse proto.InternalMessageInfo

func (m *GetWalletMiningIncomeResponse) GetMiningIncome() string {
	if m != nil {
		return m.MiningIncome
	}
	return ""
}

func (m *GetWalletMiningIncomeResponse) GetUserProfile() *ProfileResponse {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

type GetGatewayMiningIncomeRequest struct {
	// MAC address of the gateway
	GatewayMac string `protobuf:"bytes,1,opt,name=gateway_mac,json=gatewayMac,proto3" json:"gateway_mac,omitempty"`
	// Organization ID
	OrgId int64 `protobuf:"varint,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	// Return mining stats for the period starting at from_date and ending at
	// till_date inclusive
	FromDate             *timestamp.Timestamp `protobuf:"bytes,3,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	TillDate             *timestamp.Timestamp `protobuf:"bytes,4,opt,name=till_date,json=tillDate,proto3" json:"till_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetGatewayMiningIncomeRequest) Reset()         { *m = GetGatewayMiningIncomeRequest{} }
func (m *GetGatewayMiningIncomeRequest) String() string { return proto.CompactTextString(m) }
func (*GetGatewayMiningIncomeRequest) ProtoMessage()    {}
func (*GetGatewayMiningIncomeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{4}
}

func (m *GetGatewayMiningIncomeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGatewayMiningIncomeRequest.Unmarshal(m, b)
}
func (m *GetGatewayMiningIncomeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGatewayMiningIncomeRequest.Marshal(b, m, deterministic)
}
func (m *GetGatewayMiningIncomeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGatewayMiningIncomeRequest.Merge(m, src)
}
func (m *GetGatewayMiningIncomeRequest) XXX_Size() int {
	return xxx_messageInfo_GetGatewayMiningIncomeRequest.Size(m)
}
func (m *GetGatewayMiningIncomeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGatewayMiningIncomeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGatewayMiningIncomeRequest proto.InternalMessageInfo

func (m *GetGatewayMiningIncomeRequest) GetGatewayMac() string {
	if m != nil {
		return m.GatewayMac
	}
	return ""
}

func (m *GetGatewayMiningIncomeRequest) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *GetGatewayMiningIncomeRequest) GetFromDate() *timestamp.Timestamp {
	if m != nil {
		return m.FromDate
	}
	return nil
}

func (m *GetGatewayMiningIncomeRequest) GetTillDate() *timestamp.Timestamp {
	if m != nil {
		return m.TillDate
	}
	return nil
}

// Mining stats for a single date
type MiningStats struct {
	// date on which the mining happened
	Date *timestamp.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	// amount mined on the specified day
	Amount               string   `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MiningStats) Reset()         { *m = MiningStats{} }
func (m *MiningStats) String() string { return proto.CompactTextString(m) }
func (*MiningStats) ProtoMessage()    {}
func (*MiningStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{5}
}

func (m *MiningStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MiningStats.Unmarshal(m, b)
}
func (m *MiningStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MiningStats.Marshal(b, m, deterministic)
}
func (m *MiningStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MiningStats.Merge(m, src)
}
func (m *MiningStats) XXX_Size() int {
	return xxx_messageInfo_MiningStats.Size(m)
}
func (m *MiningStats) XXX_DiscardUnknown() {
	xxx_messageInfo_MiningStats.DiscardUnknown(m)
}

var xxx_messageInfo_MiningStats proto.InternalMessageInfo

func (m *MiningStats) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *MiningStats) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type GetGatewayMiningIncomeResponse struct {
	// daily mining stats for each day the mining happened
	DailyStats []*MiningStats `protobuf:"bytes,1,rep,name=daily_stats,json=dailyStats,proto3" json:"daily_stats,omitempty"`
	// total amount mined by gateway during the requested period
	Total                string   `protobuf:"bytes,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGatewayMiningIncomeResponse) Reset()         { *m = GetGatewayMiningIncomeResponse{} }
func (m *GetGatewayMiningIncomeResponse) String() string { return proto.CompactTextString(m) }
func (*GetGatewayMiningIncomeResponse) ProtoMessage()    {}
func (*GetGatewayMiningIncomeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{6}
}

func (m *GetGatewayMiningIncomeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGatewayMiningIncomeResponse.Unmarshal(m, b)
}
func (m *GetGatewayMiningIncomeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGatewayMiningIncomeResponse.Marshal(b, m, deterministic)
}
func (m *GetGatewayMiningIncomeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGatewayMiningIncomeResponse.Merge(m, src)
}
func (m *GetGatewayMiningIncomeResponse) XXX_Size() int {
	return xxx_messageInfo_GetGatewayMiningIncomeResponse.Size(m)
}
func (m *GetGatewayMiningIncomeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGatewayMiningIncomeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetGatewayMiningIncomeResponse proto.InternalMessageInfo

func (m *GetGatewayMiningIncomeResponse) GetDailyStats() []*MiningStats {
	if m != nil {
		return m.DailyStats
	}
	return nil
}

func (m *GetGatewayMiningIncomeResponse) GetTotal() string {
	if m != nil {
		return m.Total
	}
	return ""
}

type MiningData struct {
	Month                string   `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
	Amount               string   `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MiningData) Reset()         { *m = MiningData{} }
func (m *MiningData) String() string { return proto.CompactTextString(m) }
func (*MiningData) ProtoMessage()    {}
func (*MiningData) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{7}
}

func (m *MiningData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MiningData.Unmarshal(m, b)
}
func (m *MiningData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MiningData.Marshal(b, m, deterministic)
}
func (m *MiningData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MiningData.Merge(m, src)
}
func (m *MiningData) XXX_Size() int {
	return xxx_messageInfo_MiningData.Size(m)
}
func (m *MiningData) XXX_DiscardUnknown() {
	xxx_messageInfo_MiningData.DiscardUnknown(m)
}

var xxx_messageInfo_MiningData proto.InternalMessageInfo

func (m *MiningData) GetMonth() string {
	if m != nil {
		return m.Month
	}
	return ""
}

func (m *MiningData) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type GetMiningInfoRequest struct {
	OrgId                int64    `protobuf:"varint,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMiningInfoRequest) Reset()         { *m = GetMiningInfoRequest{} }
func (m *GetMiningInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetMiningInfoRequest) ProtoMessage()    {}
func (*GetMiningInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{8}
}

func (m *GetMiningInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMiningInfoRequest.Unmarshal(m, b)
}
func (m *GetMiningInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMiningInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetMiningInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMiningInfoRequest.Merge(m, src)
}
func (m *GetMiningInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetMiningInfoRequest.Size(m)
}
func (m *GetMiningInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMiningInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMiningInfoRequest proto.InternalMessageInfo

func (m *GetMiningInfoRequest) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

type GetMiningInfoResponse struct {
	TodayRev             string        `protobuf:"bytes,1,opt,name=todayRev,proto3" json:"todayRev,omitempty"`
	Data                 []*MiningData `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetMiningInfoResponse) Reset()         { *m = GetMiningInfoResponse{} }
func (m *GetMiningInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetMiningInfoResponse) ProtoMessage()    {}
func (*GetMiningInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{9}
}

func (m *GetMiningInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMiningInfoResponse.Unmarshal(m, b)
}
func (m *GetMiningInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMiningInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetMiningInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMiningInfoResponse.Merge(m, src)
}
func (m *GetMiningInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetMiningInfoResponse.Size(m)
}
func (m *GetMiningInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMiningInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMiningInfoResponse proto.InternalMessageInfo

func (m *GetMiningInfoResponse) GetTodayRev() string {
	if m != nil {
		return m.TodayRev
	}
	return ""
}

func (m *GetMiningInfoResponse) GetData() []*MiningData {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetVmxcTxHistoryRequest struct {
	OrgId                int64    `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Offset               int64    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int64    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVmxcTxHistoryRequest) Reset()         { *m = GetVmxcTxHistoryRequest{} }
func (m *GetVmxcTxHistoryRequest) String() string { return proto.CompactTextString(m) }
func (*GetVmxcTxHistoryRequest) ProtoMessage()    {}
func (*GetVmxcTxHistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{10}
}

func (m *GetVmxcTxHistoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVmxcTxHistoryRequest.Unmarshal(m, b)
}
func (m *GetVmxcTxHistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVmxcTxHistoryRequest.Marshal(b, m, deterministic)
}
func (m *GetVmxcTxHistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVmxcTxHistoryRequest.Merge(m, src)
}
func (m *GetVmxcTxHistoryRequest) XXX_Size() int {
	return xxx_messageInfo_GetVmxcTxHistoryRequest.Size(m)
}
func (m *GetVmxcTxHistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVmxcTxHistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVmxcTxHistoryRequest proto.InternalMessageInfo

func (m *GetVmxcTxHistoryRequest) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *GetVmxcTxHistoryRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetVmxcTxHistoryRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type VmxcTxHistory struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	TxType               string   `protobuf:"bytes,3,opt,name=tx_type,json=txType,proto3" json:"tx_type,omitempty"`
	Amount               float64  `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VmxcTxHistory) Reset()         { *m = VmxcTxHistory{} }
func (m *VmxcTxHistory) String() string { return proto.CompactTextString(m) }
func (*VmxcTxHistory) ProtoMessage()    {}
func (*VmxcTxHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{11}
}

func (m *VmxcTxHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VmxcTxHistory.Unmarshal(m, b)
}
func (m *VmxcTxHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VmxcTxHistory.Marshal(b, m, deterministic)
}
func (m *VmxcTxHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VmxcTxHistory.Merge(m, src)
}
func (m *VmxcTxHistory) XXX_Size() int {
	return xxx_messageInfo_VmxcTxHistory.Size(m)
}
func (m *VmxcTxHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_VmxcTxHistory.DiscardUnknown(m)
}

var xxx_messageInfo_VmxcTxHistory proto.InternalMessageInfo

func (m *VmxcTxHistory) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *VmxcTxHistory) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *VmxcTxHistory) GetTxType() string {
	if m != nil {
		return m.TxType
	}
	return ""
}

func (m *VmxcTxHistory) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *VmxcTxHistory) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type GetVmxcTxHistoryResponse struct {
	Count                int64            `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	TxHistory            []*VmxcTxHistory `protobuf:"bytes,2,rep,name=tx_history,json=txHistory,proto3" json:"tx_history,omitempty"`
	UserProfile          *ProfileResponse `protobuf:"bytes,3,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetVmxcTxHistoryResponse) Reset()         { *m = GetVmxcTxHistoryResponse{} }
func (m *GetVmxcTxHistoryResponse) String() string { return proto.CompactTextString(m) }
func (*GetVmxcTxHistoryResponse) ProtoMessage()    {}
func (*GetVmxcTxHistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{12}
}

func (m *GetVmxcTxHistoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVmxcTxHistoryResponse.Unmarshal(m, b)
}
func (m *GetVmxcTxHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVmxcTxHistoryResponse.Marshal(b, m, deterministic)
}
func (m *GetVmxcTxHistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVmxcTxHistoryResponse.Merge(m, src)
}
func (m *GetVmxcTxHistoryResponse) XXX_Size() int {
	return xxx_messageInfo_GetVmxcTxHistoryResponse.Size(m)
}
func (m *GetVmxcTxHistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVmxcTxHistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVmxcTxHistoryResponse proto.InternalMessageInfo

func (m *GetVmxcTxHistoryResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GetVmxcTxHistoryResponse) GetTxHistory() []*VmxcTxHistory {
	if m != nil {
		return m.TxHistory
	}
	return nil
}

func (m *GetVmxcTxHistoryResponse) GetUserProfile() *ProfileResponse {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

type GetNetworkUsageHistRequest struct {
	OrgId                int64                `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Currency             string               `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	From                 *timestamp.Timestamp `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	Till                 *timestamp.Timestamp `protobuf:"bytes,4,opt,name=till,proto3" json:"till,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetNetworkUsageHistRequest) Reset()         { *m = GetNetworkUsageHistRequest{} }
func (m *GetNetworkUsageHistRequest) String() string { return proto.CompactTextString(m) }
func (*GetNetworkUsageHistRequest) ProtoMessage()    {}
func (*GetNetworkUsageHistRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{13}
}

func (m *GetNetworkUsageHistRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNetworkUsageHistRequest.Unmarshal(m, b)
}
func (m *GetNetworkUsageHistRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNetworkUsageHistRequest.Marshal(b, m, deterministic)
}
func (m *GetNetworkUsageHistRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNetworkUsageHistRequest.Merge(m, src)
}
func (m *GetNetworkUsageHistRequest) XXX_Size() int {
	return xxx_messageInfo_GetNetworkUsageHistRequest.Size(m)
}
func (m *GetNetworkUsageHistRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNetworkUsageHistRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNetworkUsageHistRequest proto.InternalMessageInfo

func (m *GetNetworkUsageHistRequest) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *GetNetworkUsageHistRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *GetNetworkUsageHistRequest) GetFrom() *timestamp.Timestamp {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *GetNetworkUsageHistRequest) GetTill() *timestamp.Timestamp {
	if m != nil {
		return m.Till
	}
	return nil
}

type NetworkUsage struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Amount               string               `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	DlCntDev             int64                `protobuf:"varint,3,opt,name=dl_cnt_dev,json=dlCntDev,proto3" json:"dl_cnt_dev,omitempty"`
	DlCntDevFree         int64                `protobuf:"varint,4,opt,name=dl_cnt_dev_free,json=dlCntDevFree,proto3" json:"dl_cnt_dev_free,omitempty"`
	UlCntDev             int64                `protobuf:"varint,5,opt,name=ul_cnt_dev,json=ulCntDev,proto3" json:"ul_cnt_dev,omitempty"`
	UlCntDevFree         int64                `protobuf:"varint,6,opt,name=ul_cnt_dev_free,json=ulCntDevFree,proto3" json:"ul_cnt_dev_free,omitempty"`
	DlCntGw              int64                `protobuf:"varint,7,opt,name=dl_cnt_gw,json=dlCntGw,proto3" json:"dl_cnt_gw,omitempty"`
	DlCntGwFree          int64                `protobuf:"varint,8,opt,name=dl_cnt_gw_free,json=dlCntGwFree,proto3" json:"dl_cnt_gw_free,omitempty"`
	UlCntGw              int64                `protobuf:"varint,9,opt,name=ul_cnt_gw,json=ulCntGw,proto3" json:"ul_cnt_gw,omitempty"`
	UlCntGwFree          int64                `protobuf:"varint,10,opt,name=ul_cnt_gw_free,json=ulCntGwFree,proto3" json:"ul_cnt_gw_free,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *NetworkUsage) Reset()         { *m = NetworkUsage{} }
func (m *NetworkUsage) String() string { return proto.CompactTextString(m) }
func (*NetworkUsage) ProtoMessage()    {}
func (*NetworkUsage) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{14}
}

func (m *NetworkUsage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkUsage.Unmarshal(m, b)
}
func (m *NetworkUsage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkUsage.Marshal(b, m, deterministic)
}
func (m *NetworkUsage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkUsage.Merge(m, src)
}
func (m *NetworkUsage) XXX_Size() int {
	return xxx_messageInfo_NetworkUsage.Size(m)
}
func (m *NetworkUsage) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkUsage.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkUsage proto.InternalMessageInfo

func (m *NetworkUsage) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *NetworkUsage) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *NetworkUsage) GetDlCntDev() int64 {
	if m != nil {
		return m.DlCntDev
	}
	return 0
}

func (m *NetworkUsage) GetDlCntDevFree() int64 {
	if m != nil {
		return m.DlCntDevFree
	}
	return 0
}

func (m *NetworkUsage) GetUlCntDev() int64 {
	if m != nil {
		return m.UlCntDev
	}
	return 0
}

func (m *NetworkUsage) GetUlCntDevFree() int64 {
	if m != nil {
		return m.UlCntDevFree
	}
	return 0
}

func (m *NetworkUsage) GetDlCntGw() int64 {
	if m != nil {
		return m.DlCntGw
	}
	return 0
}

func (m *NetworkUsage) GetDlCntGwFree() int64 {
	if m != nil {
		return m.DlCntGwFree
	}
	return 0
}

func (m *NetworkUsage) GetUlCntGw() int64 {
	if m != nil {
		return m.UlCntGw
	}
	return 0
}

func (m *NetworkUsage) GetUlCntGwFree() int64 {
	if m != nil {
		return m.UlCntGwFree
	}
	return 0
}

type GetNetworkUsageHistResponse struct {
	NetworkUsage         []*NetworkUsage  `protobuf:"bytes,1,rep,name=network_usage,json=networkUsage,proto3" json:"network_usage,omitempty"`
	UserProfile          *ProfileResponse `protobuf:"bytes,2,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	Count                int64            `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetNetworkUsageHistResponse) Reset()         { *m = GetNetworkUsageHistResponse{} }
func (m *GetNetworkUsageHistResponse) String() string { return proto.CompactTextString(m) }
func (*GetNetworkUsageHistResponse) ProtoMessage()    {}
func (*GetNetworkUsageHistResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{15}
}

func (m *GetNetworkUsageHistResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNetworkUsageHistResponse.Unmarshal(m, b)
}
func (m *GetNetworkUsageHistResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNetworkUsageHistResponse.Marshal(b, m, deterministic)
}
func (m *GetNetworkUsageHistResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNetworkUsageHistResponse.Merge(m, src)
}
func (m *GetNetworkUsageHistResponse) XXX_Size() int {
	return xxx_messageInfo_GetNetworkUsageHistResponse.Size(m)
}
func (m *GetNetworkUsageHistResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNetworkUsageHistResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNetworkUsageHistResponse proto.InternalMessageInfo

func (m *GetNetworkUsageHistResponse) GetNetworkUsage() []*NetworkUsage {
	if m != nil {
		return m.NetworkUsage
	}
	return nil
}

func (m *GetNetworkUsageHistResponse) GetUserProfile() *ProfileResponse {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

func (m *GetNetworkUsageHistResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetDownLinkPriceRequest struct {
	OrgId                int64    `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDownLinkPriceRequest) Reset()         { *m = GetDownLinkPriceRequest{} }
func (m *GetDownLinkPriceRequest) String() string { return proto.CompactTextString(m) }
func (*GetDownLinkPriceRequest) ProtoMessage()    {}
func (*GetDownLinkPriceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{16}
}

func (m *GetDownLinkPriceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDownLinkPriceRequest.Unmarshal(m, b)
}
func (m *GetDownLinkPriceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDownLinkPriceRequest.Marshal(b, m, deterministic)
}
func (m *GetDownLinkPriceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDownLinkPriceRequest.Merge(m, src)
}
func (m *GetDownLinkPriceRequest) XXX_Size() int {
	return xxx_messageInfo_GetDownLinkPriceRequest.Size(m)
}
func (m *GetDownLinkPriceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDownLinkPriceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDownLinkPriceRequest proto.InternalMessageInfo

func (m *GetDownLinkPriceRequest) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

type GetDownLinkPriceResponse struct {
	DownLinkPrice        float64          `protobuf:"fixed64,1,opt,name=down_link_price,json=downLinkPrice,proto3" json:"down_link_price,omitempty"`
	UserProfile          *ProfileResponse `protobuf:"bytes,2,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetDownLinkPriceResponse) Reset()         { *m = GetDownLinkPriceResponse{} }
func (m *GetDownLinkPriceResponse) String() string { return proto.CompactTextString(m) }
func (*GetDownLinkPriceResponse) ProtoMessage()    {}
func (*GetDownLinkPriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{17}
}

func (m *GetDownLinkPriceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDownLinkPriceResponse.Unmarshal(m, b)
}
func (m *GetDownLinkPriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDownLinkPriceResponse.Marshal(b, m, deterministic)
}
func (m *GetDownLinkPriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDownLinkPriceResponse.Merge(m, src)
}
func (m *GetDownLinkPriceResponse) XXX_Size() int {
	return xxx_messageInfo_GetDownLinkPriceResponse.Size(m)
}
func (m *GetDownLinkPriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDownLinkPriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDownLinkPriceResponse proto.InternalMessageInfo

func (m *GetDownLinkPriceResponse) GetDownLinkPrice() float64 {
	if m != nil {
		return m.DownLinkPrice
	}
	return 0
}

func (m *GetDownLinkPriceResponse) GetUserProfile() *ProfileResponse {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

type GetMXCpriceRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrgId                int64    `protobuf:"varint,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	MxcPrice             string   `protobuf:"bytes,3,opt,name=mxc_price,json=mxcPrice,proto3" json:"mxc_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMXCpriceRequest) Reset()         { *m = GetMXCpriceRequest{} }
func (m *GetMXCpriceRequest) String() string { return proto.CompactTextString(m) }
func (*GetMXCpriceRequest) ProtoMessage()    {}
func (*GetMXCpriceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{18}
}

func (m *GetMXCpriceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMXCpriceRequest.Unmarshal(m, b)
}
func (m *GetMXCpriceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMXCpriceRequest.Marshal(b, m, deterministic)
}
func (m *GetMXCpriceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMXCpriceRequest.Merge(m, src)
}
func (m *GetMXCpriceRequest) XXX_Size() int {
	return xxx_messageInfo_GetMXCpriceRequest.Size(m)
}
func (m *GetMXCpriceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMXCpriceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMXCpriceRequest proto.InternalMessageInfo

func (m *GetMXCpriceRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetMXCpriceRequest) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *GetMXCpriceRequest) GetMxcPrice() string {
	if m != nil {
		return m.MxcPrice
	}
	return ""
}

type GetMXCpriceResponse struct {
	MxcPrice             string   `protobuf:"bytes,1,opt,name=mxc_price,json=mxcPrice,proto3" json:"mxc_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMXCpriceResponse) Reset()         { *m = GetMXCpriceResponse{} }
func (m *GetMXCpriceResponse) String() string { return proto.CompactTextString(m) }
func (*GetMXCpriceResponse) ProtoMessage()    {}
func (*GetMXCpriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{19}
}

func (m *GetMXCpriceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMXCpriceResponse.Unmarshal(m, b)
}
func (m *GetMXCpriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMXCpriceResponse.Marshal(b, m, deterministic)
}
func (m *GetMXCpriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMXCpriceResponse.Merge(m, src)
}
func (m *GetMXCpriceResponse) XXX_Size() int {
	return xxx_messageInfo_GetMXCpriceResponse.Size(m)
}
func (m *GetMXCpriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMXCpriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMXCpriceResponse proto.InternalMessageInfo

func (m *GetMXCpriceResponse) GetMxcPrice() string {
	if m != nil {
		return m.MxcPrice
	}
	return ""
}

func init() {
	proto.RegisterType((*GetWalletBalanceRequest)(nil), "appserver_serves_ui.GetWalletBalanceRequest")
	proto.RegisterType((*GetWalletBalanceResponse)(nil), "appserver_serves_ui.GetWalletBalanceResponse")
	proto.RegisterType((*GetWalletMiningIncomeRequest)(nil), "appserver_serves_ui.GetWalletMiningIncomeRequest")
	proto.RegisterType((*GetWalletMiningIncomeResponse)(nil), "appserver_serves_ui.GetWalletMiningIncomeResponse")
	proto.RegisterType((*GetGatewayMiningIncomeRequest)(nil), "appserver_serves_ui.GetGatewayMiningIncomeRequest")
	proto.RegisterType((*MiningStats)(nil), "appserver_serves_ui.MiningStats")
	proto.RegisterType((*GetGatewayMiningIncomeResponse)(nil), "appserver_serves_ui.GetGatewayMiningIncomeResponse")
	proto.RegisterType((*MiningData)(nil), "appserver_serves_ui.MiningData")
	proto.RegisterType((*GetMiningInfoRequest)(nil), "appserver_serves_ui.GetMiningInfoRequest")
	proto.RegisterType((*GetMiningInfoResponse)(nil), "appserver_serves_ui.GetMiningInfoResponse")
	proto.RegisterType((*GetVmxcTxHistoryRequest)(nil), "appserver_serves_ui.GetVmxcTxHistoryRequest")
	proto.RegisterType((*VmxcTxHistory)(nil), "appserver_serves_ui.VmxcTxHistory")
	proto.RegisterType((*GetVmxcTxHistoryResponse)(nil), "appserver_serves_ui.GetVmxcTxHistoryResponse")
	proto.RegisterType((*GetNetworkUsageHistRequest)(nil), "appserver_serves_ui.GetNetworkUsageHistRequest")
	proto.RegisterType((*NetworkUsage)(nil), "appserver_serves_ui.NetworkUsage")
	proto.RegisterType((*GetNetworkUsageHistResponse)(nil), "appserver_serves_ui.GetNetworkUsageHistResponse")
	proto.RegisterType((*GetDownLinkPriceRequest)(nil), "appserver_serves_ui.GetDownLinkPriceRequest")
	proto.RegisterType((*GetDownLinkPriceResponse)(nil), "appserver_serves_ui.GetDownLinkPriceResponse")
	proto.RegisterType((*GetMXCpriceRequest)(nil), "appserver_serves_ui.GetMXCpriceRequest")
	proto.RegisterType((*GetMXCpriceResponse)(nil), "appserver_serves_ui.GetMXCpriceResponse")
}

func init() { proto.RegisterFile("wallet.proto", fileDescriptor_b88fd140af4deb6f) }

var fileDescriptor_b88fd140af4deb6f = []byte{
	// 1257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x4b, 0x6f, 0xe3, 0xd4,
	0x17, 0x97, 0x93, 0x69, 0x9a, 0x9c, 0x24, 0x9d, 0xbf, 0x6e, 0x5f, 0x19, 0xb7, 0x9d, 0xb6, 0x6e,
	0xe7, 0x3f, 0x65, 0xa0, 0xc9, 0xd0, 0x2e, 0x40, 0xec, 0xca, 0x54, 0x13, 0x2a, 0x31, 0x68, 0xe4,
	0xe9, 0x00, 0x2b, 0xac, 0x5b, 0xfb, 0x26, 0xb5, 0x6a, 0xfb, 0x06, 0xfb, 0xba, 0x49, 0x84, 0x46,
	0x48, 0xb0, 0x60, 0x01, 0xac, 0x90, 0x10, 0x5b, 0x24, 0x24, 0x96, 0x88, 0x3d, 0x4b, 0x36, 0x6c,
	0xe1, 0x2b, 0xb0, 0xe4, 0x43, 0xa0, 0xfb, 0x48, 0x62, 0xa7, 0x76, 0x1f, 0xa8, 0x2b, 0xeb, 0xdc,
	0x7b, 0x1e, 0xbf, 0xf3, 0xbb, 0xe7, 0x1c, 0x1f, 0xa8, 0xf5, 0xb1, 0xe7, 0x11, 0xd6, 0xec, 0x85,
	0x94, 0x51, 0x34, 0x8f, 0x7b, 0xbd, 0x88, 0x84, 0xe7, 0x24, 0xb4, 0xc4, 0x27, 0xb2, 0x62, 0x57,
	0x5f, 0xed, 0x52, 0xda, 0xf5, 0x48, 0x0b, 0xf7, 0xdc, 0x16, 0x0e, 0x02, 0xca, 0x30, 0x73, 0x69,
	0x10, 0x49, 0x13, 0x7d, 0x5d, 0xdd, 0x0a, 0xe9, 0x24, 0xee, 0xb4, 0x98, 0xeb, 0x93, 0x88, 0x61,
	0xbf, 0xa7, 0x14, 0xe6, 0xdc, 0x80, 0x91, 0x30, 0xc0, 0x9e, 0x94, 0x0d, 0x02, 0xcb, 0x6d, 0xc2,
	0x3e, 0x12, 0x61, 0xdf, 0xc5, 0x1e, 0x0e, 0x6c, 0x62, 0x92, 0x4f, 0x63, 0x12, 0x31, 0xb4, 0x0c,
	0xb3, 0x71, 0x44, 0x42, 0xcb, 0x75, 0x1a, 0xda, 0x86, 0xb6, 0x53, 0x34, 0x4b, 0x5c, 0x3c, 0x72,
	0xd0, 0x22, 0x94, 0x68, 0xd8, 0xe5, 0xe7, 0x05, 0x71, 0x3e, 0x43, 0xc3, 0xee, 0x91, 0x83, 0x74,
	0x28, 0xdb, 0x71, 0x18, 0x92, 0xc0, 0x1e, 0x36, 0x8a, 0x1b, 0xda, 0x4e, 0xc5, 0x1c, 0xcb, 0xc6,
	0x2b, 0x68, 0x5c, 0x0c, 0x13, 0xf5, 0x68, 0x10, 0x11, 0xd4, 0x80, 0xd9, 0x13, 0x79, 0x24, 0xe2,
	0x54, 0xcc, 0x91, 0x88, 0xda, 0x50, 0x13, 0x08, 0x7a, 0x21, 0xed, 0xb8, 0x1e, 0x11, 0xe1, 0xaa,
	0x7b, 0xdb, 0xcd, 0x0c, 0x5e, 0x9a, 0xcf, 0xa5, 0xce, 0xc8, 0xab, 0x59, 0xe5, 0x96, 0xea, 0xd0,
	0xf8, 0x55, 0x83, 0xd5, 0x71, 0xfc, 0x67, 0x6e, 0xe0, 0x06, 0xdd, 0xa3, 0xc0, 0xa6, 0xfe, 0x38,
	0xd7, 0x9b, 0xa7, 0x84, 0x9a, 0x70, 0xa7, 0x13, 0x52, 0xbf, 0x71, 0x47, 0x80, 0xd2, 0x9b, 0x92,
	0xf9, 0xe6, 0x88, 0xf9, 0xe6, 0xf1, 0x88, 0x79, 0x53, 0xe8, 0x71, 0x7d, 0xe6, 0x7a, 0x5e, 0x63,
	0xe6, 0x6a, 0x7d, 0xae, 0x67, 0x7c, 0xab, 0xc1, 0x5a, 0x0e, 0x66, 0x45, 0xdc, 0x16, 0xd4, 0x7d,
	0x71, 0x6e, 0xb9, 0xe2, 0x42, 0xd1, 0x57, 0xf3, 0x13, 0xca, 0xb7, 0xc7, 0xe1, 0x1f, 0x12, 0x4f,
	0x1b, 0x33, 0xd2, 0xc7, 0xc3, 0x2c, 0x12, 0xd7, 0xa1, 0xda, 0x95, 0xb7, 0x96, 0x8f, 0x6d, 0x85,
	0x06, 0xd4, 0xd1, 0x33, 0x6c, 0xe7, 0xb1, 0xfc, 0x16, 0x54, 0x38, 0x43, 0x96, 0x83, 0x19, 0x11,
	0x34, 0x5f, 0x4e, 0x4f, 0x99, 0x2b, 0x1f, 0x62, 0x46, 0xb8, 0x21, 0xa7, 0x4a, 0x1a, 0x5e, 0xfd,
	0x0e, 0x65, 0xae, 0xcc, 0x0d, 0x8d, 0x97, 0x50, 0x95, 0x09, 0xbc, 0x60, 0x98, 0x45, 0xfc, 0x69,
	0x84, 0x0b, 0xed, 0xea, 0xa7, 0xe1, 0x7a, 0x68, 0x09, 0x4a, 0xd8, 0xa7, 0x71, 0xc0, 0x44, 0x1e,
	0x15, 0x53, 0x49, 0xc6, 0x10, 0xee, 0xe7, 0x31, 0xa4, 0x9e, 0xec, 0x00, 0xaa, 0x0e, 0x76, 0xbd,
	0xa1, 0x15, 0xf1, 0xc0, 0x0d, 0x6d, 0xa3, 0xb8, 0x53, 0xdd, 0xdb, 0xc8, 0x7c, 0x8c, 0x04, 0x40,
	0x13, 0x84, 0x91, 0x04, 0xbb, 0x00, 0x33, 0x8c, 0x32, 0xec, 0xa9, 0xd8, 0x52, 0x30, 0xde, 0x01,
	0x90, 0x06, 0x87, 0x98, 0x61, 0xae, 0xe3, 0xd3, 0x80, 0x9d, 0xaa, 0x37, 0x90, 0x42, 0x2e, 0xec,
	0x5d, 0x58, 0x68, 0x4f, 0x4a, 0xac, 0x43, 0x2f, 0x6f, 0x0a, 0xe3, 0x14, 0x16, 0xa7, 0xd4, 0x55,
	0x72, 0x3a, 0x94, 0x19, 0x75, 0xf0, 0xd0, 0x24, 0xe7, 0x2a, 0xf0, 0x58, 0x46, 0xfb, 0x82, 0x62,
	0xdc, 0x28, 0x88, 0x8c, 0xd7, 0x2f, 0xc9, 0x98, 0x27, 0x20, 0x78, 0xc6, 0xc6, 0x27, 0x62, 0x38,
	0x7d, 0xe8, 0x0f, 0xec, 0xe3, 0xc1, 0x7b, 0x6e, 0xc4, 0x68, 0x38, 0xbc, 0x88, 0x4d, 0x4b, 0x96,
	0xd2, 0x12, 0x94, 0x68, 0xa7, 0x13, 0x11, 0xa6, 0x20, 0x2b, 0x89, 0x13, 0xe2, 0xb9, 0xbe, 0xcb,
	0x44, 0x79, 0x15, 0x4d, 0x29, 0x18, 0x5f, 0x6a, 0x50, 0x4f, 0x79, 0x47, 0x48, 0x35, 0xb5, 0x84,
	0x2f, 0x1b, 0x77, 0x0e, 0x0a, 0x8c, 0x2a, 0xca, 0x0a, 0x8c, 0xf2, 0xb9, 0xc8, 0x06, 0x16, 0x1b,
	0xf6, 0x88, 0x9a, 0x09, 0x25, 0x36, 0x38, 0x1e, 0xf6, 0x92, 0x65, 0xc1, 0x6b, 0x51, 0x1b, 0xf1,
	0x8b, 0xd6, 0x00, 0xec, 0x90, 0x60, 0x46, 0x1c, 0x0b, 0x33, 0xd1, 0xff, 0x15, 0xb3, 0xa2, 0x4e,
	0x0e, 0x98, 0xf1, 0x9b, 0x26, 0x86, 0xe3, 0x54, 0x9a, 0x8a, 0xd3, 0x05, 0x98, 0xb1, 0x85, 0x4b,
	0x95, 0xa6, 0x10, 0xd0, 0x01, 0x00, 0x1b, 0x58, 0xa7, 0x52, 0x57, 0x71, 0x6a, 0x64, 0x72, 0x9a,
	0xf6, 0x5a, 0x61, 0xe3, 0x4c, 0xa7, 0xe7, 0x42, 0xf1, 0xbf, 0xce, 0x85, 0x5f, 0x34, 0xd0, 0xdb,
	0x84, 0x7d, 0x40, 0x58, 0x9f, 0x86, 0x67, 0x2f, 0x23, 0xdc, 0x25, 0x3c, 0xc6, 0x15, 0x0f, 0x95,
	0x9c, 0xac, 0x85, 0x9c, 0xc9, 0x5a, 0xbc, 0xe1, 0x64, 0xbd, 0x73, 0xcd, 0xc9, 0xfa, 0x4f, 0x01,
	0x6a, 0x49, 0xb8, 0xe8, 0x6d, 0x3e, 0x47, 0x94, 0xce, 0x35, 0x86, 0xc0, 0x44, 0x39, 0xaf, 0xa5,
	0xd0, 0x2a, 0x80, 0xe3, 0x59, 0x76, 0xc0, 0x2c, 0x87, 0x9c, 0xab, 0xa2, 0x2b, 0x3b, 0xde, 0x93,
	0x80, 0x1d, 0x92, 0x73, 0xf4, 0x00, 0xee, 0x4e, 0x6e, 0xad, 0x4e, 0x48, 0xe4, 0xf4, 0x2a, 0x9a,
	0xb5, 0x91, 0xca, 0xd3, 0x90, 0x10, 0xee, 0x24, 0x9e, 0x38, 0x99, 0x91, 0x4e, 0xe2, 0x84, 0x93,
	0x78, 0xca, 0x49, 0x49, 0x3a, 0x89, 0x93, 0x4e, 0x74, 0xa8, 0xa8, 0x58, 0xdd, 0x7e, 0x63, 0x56,
	0x28, 0xcc, 0x8a, 0x28, 0xed, 0x3e, 0xda, 0x82, 0xb9, 0xf1, 0x9d, 0xf4, 0x50, 0x16, 0x0a, 0x55,
	0xa5, 0x30, 0x72, 0x10, 0x8f, 0x1d, 0x54, 0xa4, 0x83, 0x78, 0xe2, 0x20, 0x4e, 0x3b, 0x00, 0xe9,
	0x20, 0x9e, 0x38, 0x30, 0x7e, 0xd7, 0x60, 0x25, 0xb3, 0x40, 0x54, 0x89, 0x3f, 0x85, 0x7a, 0x20,
	0xef, 0xac, 0x98, 0x5f, 0xaa, 0xa9, 0xb8, 0x99, 0x59, 0x8a, 0x49, 0x2f, 0x66, 0x2d, 0x48, 0xbe,
	0xe2, 0x6d, 0xfd, 0xe9, 0x26, 0x3d, 0x57, 0x4c, 0xf4, 0x9c, 0xf1, 0x58, 0x0c, 0xa3, 0x43, 0xda,
	0x0f, 0xde, 0x77, 0x83, 0xb3, 0xe7, 0xa1, 0x6b, 0x93, 0xcb, 0x6b, 0xdc, 0xf8, 0x5a, 0x36, 0xf6,
	0x94, 0x89, 0xca, 0xfa, 0xff, 0x70, 0xd7, 0xa1, 0xfd, 0xc0, 0xf2, 0xdc, 0xe0, 0xcc, 0xea, 0xf1,
	0x2b, 0x61, 0xac, 0x99, 0x75, 0x27, 0xa9, 0x7f, 0x7b, 0xff, 0x6f, 0x0c, 0x88, 0x8f, 0xed, 0x8f,
	0x9f, 0xf4, 0x92, 0xd0, 0x6f, 0xba, 0xe4, 0xad, 0x40, 0xc5, 0x1f, 0xd8, 0x0a, 0xb0, 0x5a, 0x89,
	0xfc, 0x81, 0x2d, 0xb0, 0x1a, 0x7b, 0x30, 0x9f, 0x0a, 0xa1, 0x52, 0x4d, 0xd9, 0x68, 0x69, 0x9b,
	0xbd, 0x3f, 0x2b, 0x50, 0x97, 0x3b, 0xce, 0x0b, 0x12, 0x9e, 0xf3, 0x8c, 0xbf, 0xd1, 0xe0, 0x7f,
	0xd3, 0xcb, 0x22, 0x7a, 0x23, 0x33, 0xe1, 0x9c, 0xd5, 0x55, 0xdf, 0xbd, 0xa6, 0xb6, 0x04, 0x68,
	0xac, 0x7c, 0xf1, 0xd7, 0xdf, 0xdf, 0x15, 0x16, 0xd1, 0xbc, 0xd8, 0xaa, 0xe5, 0x0e, 0xde, 0x1a,
	0x2d, 0xa1, 0x3f, 0x48, 0x38, 0xe9, 0xff, 0x44, 0x2e, 0x9c, 0xac, 0x9f, 0x55, 0x3e, 0x9c, 0xcc,
	0x99, 0x6f, 0x3c, 0x14, 0x70, 0x36, 0xd1, 0x7a, 0x12, 0xce, 0x67, 0xf2, 0x35, 0x5e, 0xb5, 0xd8,
	0x60, 0x57, 0x0d, 0x7e, 0xf4, 0x93, 0x26, 0x08, 0x9f, 0xee, 0x2c, 0xd4, 0xca, 0x8b, 0x97, 0x33,
	0xa4, 0xf5, 0xc7, 0xd7, 0x37, 0x50, 0x18, 0x1f, 0x09, 0x8c, 0xdb, 0xc8, 0xc8, 0xc4, 0x28, 0xfa,
	0x78, 0x0c, 0xf3, 0x7b, 0x0d, 0x80, 0xf7, 0x81, 0x27, 0x2b, 0x3a, 0x97, 0xbb, 0xac, 0xde, 0xca,
	0xe7, 0x2e, 0xb3, 0xad, 0x8c, 0xd7, 0x05, 0xae, 0x07, 0x68, 0x2b, 0x13, 0x17, 0x6f, 0xad, 0x49,
	0xc3, 0xa1, 0x1f, 0x35, 0xb1, 0xca, 0x5c, 0x5c, 0xb1, 0xd1, 0x9b, 0x97, 0x17, 0x50, 0xc6, 0xf6,
	0xab, 0xef, 0xdd, 0xc4, 0x44, 0xa1, 0xdd, 0x14, 0x68, 0x57, 0xd0, 0xbd, 0x24, 0xda, 0xd4, 0x4e,
	0x8f, 0x7e, 0xd6, 0x60, 0x29, 0x7b, 0xa9, 0x44, 0xb9, 0x11, 0xf3, 0x77, 0x74, 0x7d, 0xff, 0x46,
	0x36, 0x0a, 0xe6, 0xb6, 0x80, 0x79, 0x1f, 0xad, 0xe6, 0xc2, 0xb4, 0xba, 0x7d, 0xf4, 0x95, 0x06,
	0xf5, 0xd4, 0x62, 0x88, 0x5e, 0xcb, 0x0b, 0x76, 0x61, 0xd7, 0xd4, 0x1f, 0x5d, 0x47, 0x55, 0xc1,
	0x59, 0x17, 0x70, 0xee, 0xa1, 0xe5, 0x4c, 0x38, 0x1d, 0x8a, 0x3e, 0x87, 0x6a, 0x62, 0x0e, 0xa1,
	0x87, 0xb9, 0xbe, 0xd3, 0xc3, 0x50, 0xdf, 0xb9, 0x5a, 0x51, 0x41, 0x58, 0x13, 0x10, 0x96, 0xd1,
	0x62, 0x0a, 0xc2, 0x68, 0xc8, 0x9d, 0x94, 0xc4, 0xd6, 0xb0, 0xff, 0x6f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xd1, 0xf8, 0x46, 0x42, 0xd0, 0x0f, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// WalletServiceClient is the client API for WalletService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WalletServiceClient interface {
	GetWalletBalance(ctx context.Context, in *GetWalletBalanceRequest, opts ...grpc.CallOption) (*GetWalletBalanceResponse, error)
	GetVmxcTxHistory(ctx context.Context, in *GetVmxcTxHistoryRequest, opts ...grpc.CallOption) (*GetVmxcTxHistoryResponse, error)
	GetNetworkUsageHist(ctx context.Context, in *GetNetworkUsageHistRequest, opts ...grpc.CallOption) (*GetNetworkUsageHistResponse, error)
	GetDlPrice(ctx context.Context, in *GetDownLinkPriceRequest, opts ...grpc.CallOption) (*GetDownLinkPriceResponse, error)
	GetWalletMiningIncome(ctx context.Context, in *GetWalletMiningIncomeRequest, opts ...grpc.CallOption) (*GetWalletMiningIncomeResponse, error)
	// return daily and total mining amounts for the given gateway and period of time
	GetGatewayMiningIncome(ctx context.Context, in *GetGatewayMiningIncomeRequest, opts ...grpc.CallOption) (*GetGatewayMiningIncomeResponse, error)
	GetMiningInfo(ctx context.Context, in *GetMiningInfoRequest, opts ...grpc.CallOption) (*GetMiningInfoResponse, error)
	GetMXCprice(ctx context.Context, in *GetMXCpriceRequest, opts ...grpc.CallOption) (*GetMXCpriceResponse, error)
}

type walletServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletServiceClient(cc grpc.ClientConnInterface) WalletServiceClient {
	return &walletServiceClient{cc}
}

func (c *walletServiceClient) GetWalletBalance(ctx context.Context, in *GetWalletBalanceRequest, opts ...grpc.CallOption) (*GetWalletBalanceResponse, error) {
	out := new(GetWalletBalanceResponse)
	err := c.cc.Invoke(ctx, "/appserver_serves_ui.WalletService/GetWalletBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetVmxcTxHistory(ctx context.Context, in *GetVmxcTxHistoryRequest, opts ...grpc.CallOption) (*GetVmxcTxHistoryResponse, error) {
	out := new(GetVmxcTxHistoryResponse)
	err := c.cc.Invoke(ctx, "/appserver_serves_ui.WalletService/GetVmxcTxHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetNetworkUsageHist(ctx context.Context, in *GetNetworkUsageHistRequest, opts ...grpc.CallOption) (*GetNetworkUsageHistResponse, error) {
	out := new(GetNetworkUsageHistResponse)
	err := c.cc.Invoke(ctx, "/appserver_serves_ui.WalletService/GetNetworkUsageHist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetDlPrice(ctx context.Context, in *GetDownLinkPriceRequest, opts ...grpc.CallOption) (*GetDownLinkPriceResponse, error) {
	out := new(GetDownLinkPriceResponse)
	err := c.cc.Invoke(ctx, "/appserver_serves_ui.WalletService/GetDlPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetWalletMiningIncome(ctx context.Context, in *GetWalletMiningIncomeRequest, opts ...grpc.CallOption) (*GetWalletMiningIncomeResponse, error) {
	out := new(GetWalletMiningIncomeResponse)
	err := c.cc.Invoke(ctx, "/appserver_serves_ui.WalletService/GetWalletMiningIncome", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetGatewayMiningIncome(ctx context.Context, in *GetGatewayMiningIncomeRequest, opts ...grpc.CallOption) (*GetGatewayMiningIncomeResponse, error) {
	out := new(GetGatewayMiningIncomeResponse)
	err := c.cc.Invoke(ctx, "/appserver_serves_ui.WalletService/GetGatewayMiningIncome", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetMiningInfo(ctx context.Context, in *GetMiningInfoRequest, opts ...grpc.CallOption) (*GetMiningInfoResponse, error) {
	out := new(GetMiningInfoResponse)
	err := c.cc.Invoke(ctx, "/appserver_serves_ui.WalletService/GetMiningInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetMXCprice(ctx context.Context, in *GetMXCpriceRequest, opts ...grpc.CallOption) (*GetMXCpriceResponse, error) {
	out := new(GetMXCpriceResponse)
	err := c.cc.Invoke(ctx, "/appserver_serves_ui.WalletService/GetMXCprice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServiceServer is the server API for WalletService service.
type WalletServiceServer interface {
	GetWalletBalance(context.Context, *GetWalletBalanceRequest) (*GetWalletBalanceResponse, error)
	GetVmxcTxHistory(context.Context, *GetVmxcTxHistoryRequest) (*GetVmxcTxHistoryResponse, error)
	GetNetworkUsageHist(context.Context, *GetNetworkUsageHistRequest) (*GetNetworkUsageHistResponse, error)
	GetDlPrice(context.Context, *GetDownLinkPriceRequest) (*GetDownLinkPriceResponse, error)
	GetWalletMiningIncome(context.Context, *GetWalletMiningIncomeRequest) (*GetWalletMiningIncomeResponse, error)
	// return daily and total mining amounts for the given gateway and period of time
	GetGatewayMiningIncome(context.Context, *GetGatewayMiningIncomeRequest) (*GetGatewayMiningIncomeResponse, error)
	GetMiningInfo(context.Context, *GetMiningInfoRequest) (*GetMiningInfoResponse, error)
	GetMXCprice(context.Context, *GetMXCpriceRequest) (*GetMXCpriceResponse, error)
}

// UnimplementedWalletServiceServer can be embedded to have forward compatible implementations.
type UnimplementedWalletServiceServer struct {
}

func (*UnimplementedWalletServiceServer) GetWalletBalance(ctx context.Context, req *GetWalletBalanceRequest) (*GetWalletBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWalletBalance not implemented")
}
func (*UnimplementedWalletServiceServer) GetVmxcTxHistory(ctx context.Context, req *GetVmxcTxHistoryRequest) (*GetVmxcTxHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVmxcTxHistory not implemented")
}
func (*UnimplementedWalletServiceServer) GetNetworkUsageHist(ctx context.Context, req *GetNetworkUsageHistRequest) (*GetNetworkUsageHistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNetworkUsageHist not implemented")
}
func (*UnimplementedWalletServiceServer) GetDlPrice(ctx context.Context, req *GetDownLinkPriceRequest) (*GetDownLinkPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDlPrice not implemented")
}
func (*UnimplementedWalletServiceServer) GetWalletMiningIncome(ctx context.Context, req *GetWalletMiningIncomeRequest) (*GetWalletMiningIncomeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWalletMiningIncome not implemented")
}
func (*UnimplementedWalletServiceServer) GetGatewayMiningIncome(ctx context.Context, req *GetGatewayMiningIncomeRequest) (*GetGatewayMiningIncomeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGatewayMiningIncome not implemented")
}
func (*UnimplementedWalletServiceServer) GetMiningInfo(ctx context.Context, req *GetMiningInfoRequest) (*GetMiningInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMiningInfo not implemented")
}
func (*UnimplementedWalletServiceServer) GetMXCprice(ctx context.Context, req *GetMXCpriceRequest) (*GetMXCpriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMXCprice not implemented")
}

func RegisterWalletServiceServer(s *grpc.Server, srv WalletServiceServer) {
	s.RegisterService(&_WalletService_serviceDesc, srv)
}

func _WalletService_GetWalletBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetWalletBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appserver_serves_ui.WalletService/GetWalletBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetWalletBalance(ctx, req.(*GetWalletBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetVmxcTxHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVmxcTxHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetVmxcTxHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appserver_serves_ui.WalletService/GetVmxcTxHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetVmxcTxHistory(ctx, req.(*GetVmxcTxHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetNetworkUsageHist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNetworkUsageHistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetNetworkUsageHist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appserver_serves_ui.WalletService/GetNetworkUsageHist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetNetworkUsageHist(ctx, req.(*GetNetworkUsageHistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetDlPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDownLinkPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetDlPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appserver_serves_ui.WalletService/GetDlPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetDlPrice(ctx, req.(*GetDownLinkPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetWalletMiningIncome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletMiningIncomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetWalletMiningIncome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appserver_serves_ui.WalletService/GetWalletMiningIncome",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetWalletMiningIncome(ctx, req.(*GetWalletMiningIncomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetGatewayMiningIncome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGatewayMiningIncomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetGatewayMiningIncome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appserver_serves_ui.WalletService/GetGatewayMiningIncome",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetGatewayMiningIncome(ctx, req.(*GetGatewayMiningIncomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetMiningInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMiningInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetMiningInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appserver_serves_ui.WalletService/GetMiningInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetMiningInfo(ctx, req.(*GetMiningInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetMXCprice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMXCpriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetMXCprice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appserver_serves_ui.WalletService/GetMXCprice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetMXCprice(ctx, req.(*GetMXCpriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WalletService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "appserver_serves_ui.WalletService",
	HandlerType: (*WalletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWalletBalance",
			Handler:    _WalletService_GetWalletBalance_Handler,
		},
		{
			MethodName: "GetVmxcTxHistory",
			Handler:    _WalletService_GetVmxcTxHistory_Handler,
		},
		{
			MethodName: "GetNetworkUsageHist",
			Handler:    _WalletService_GetNetworkUsageHist_Handler,
		},
		{
			MethodName: "GetDlPrice",
			Handler:    _WalletService_GetDlPrice_Handler,
		},
		{
			MethodName: "GetWalletMiningIncome",
			Handler:    _WalletService_GetWalletMiningIncome_Handler,
		},
		{
			MethodName: "GetGatewayMiningIncome",
			Handler:    _WalletService_GetGatewayMiningIncome_Handler,
		},
		{
			MethodName: "GetMiningInfo",
			Handler:    _WalletService_GetMiningInfo_Handler,
		},
		{
			MethodName: "GetMXCprice",
			Handler:    _WalletService_GetMXCprice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wallet.proto",
}
