#!/bin/bash

if [ $# -ne 3 ]; then
  echo "[ Usage ]"
  echo " ./generateAndPushDockerImage <DOCKER_HUB_USERNAME> <DOCKER_HUB_PASSWORD> <DOCKER_HUB_REPOSITORY>"
  exit 1
fi

TAG=$(git describe --tags)
# SERVICENAME should always be consistent with service name in docker-compose.yml file
SERVICENAME=appserver
# docker hub settings
DOCKER_HUB_USERNAME=$1
DOCKER_HUB_PASSWORD=$2
DOCKER_HUB_REPOSITORY=$3

if [ x"$DOCKER_HUB_USERNAME" == x ]; then
  echo "DOCKER_HUB_USERNAME is invalid"
  exit 1
fi

if [ x"$DOCKER_HUB_PASSWORD" == x ]; then
  echo "DOCKER_HUB_PASSWORD is invalid"
  exit 1
fi

if [ x"$DOCKER_HUB_REPOSITORY" == x ]; then
  echo "DOCKER_HUB_REPOSITORY is invalid"
  exit 1
fi

# build image
docker-compose -f docker-compose-create-image.yml build $SERVICENAME|tee out.txt
IMAGE_ID=$(cat out.txt |grep "Successfully built" |awk '{print $NF}')

# push image to docker hub
docker logout
docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD docker.io
docker tag $IMAGE_ID $DOCKER_HUB_REPOSITORY:$SERVICENAME.$TAG
docker push $DOCKER_HUB_REPOSITORY:$SERVICENAME.$TAG

# before exit
rm out.txt
