// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fuotaDeployment.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"
import google_protobuf3 "github.com/golang/protobuf/ptypes/duration"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type FUOTADeploymentDeviceState int32

const (
	// Pending.
	FUOTADeploymentDeviceState_PENDING FUOTADeploymentDeviceState = 0
	// Success.
	FUOTADeploymentDeviceState_SUCCESS FUOTADeploymentDeviceState = 1
	// Error.
	FUOTADeploymentDeviceState_ERROR FUOTADeploymentDeviceState = 2
)

var FUOTADeploymentDeviceState_name = map[int32]string{
	0: "PENDING",
	1: "SUCCESS",
	2: "ERROR",
}
var FUOTADeploymentDeviceState_value = map[string]int32{
	"PENDING": 0,
	"SUCCESS": 1,
	"ERROR":   2,
}

func (x FUOTADeploymentDeviceState) String() string {
	return proto.EnumName(FUOTADeploymentDeviceState_name, int32(x))
}
func (FUOTADeploymentDeviceState) EnumDescriptor() ([]byte, []int) { return fileDescriptor13, []int{0} }

type FUOTADeployment struct {
	// ID of the deployment (string formatted UUID).
	// This value will be automatically assigned on create.
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// Name of the deployment.
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// Multicast type.
	// Currently only Class-C is supported!
	GroupType MulticastGroupType `protobuf:"varint,3,opt,name=group_type,json=groupType,enum=api.MulticastGroupType" json:"group_type,omitempty"`
	// Data-rate.
	Dr uint32 `protobuf:"varint,4,opt,name=dr" json:"dr,omitempty"`
	// Frequency (Hz).
	Frequency uint32 `protobuf:"varint,5,opt,name=frequency" json:"frequency,omitempty"`
	// Payload.
	Payload []byte `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	// Redundancy (number of packages).
	Redundancy uint32 `protobuf:"varint,7,opt,name=redundancy" json:"redundancy,omitempty"`
	// Multicast time-out.
	// Please refer to the Remote Multicast Setup specification as this field
	// has a different meaning for Class-B and Class-C groups.
	MulticastTimeout uint32 `protobuf:"varint,8,opt,name=multicast_timeout,json=multicastTimeout" json:"multicast_timeout,omitempty"`
	// Unicast time-out.
	// Set this to the value in which you at least expect an uplink frame from the
	// device. The FUOTA deployment engine will wait at least for the given time
	// before proceeding with the next steps.
	UnicastTimeout *google_protobuf3.Duration `protobuf:"bytes,9,opt,name=unicast_timeout,json=unicastTimeout" json:"unicast_timeout,omitempty"`
	// Deployment state.
	// This value will be automatically set on create.
	State string `protobuf:"bytes,10,opt,name=state" json:"state,omitempty"`
	// Next step after.
	// This value will be automatically set on create.
	NextStepAfter *google_protobuf1.Timestamp `protobuf:"bytes,11,opt,name=next_step_after,json=nextStepAfter" json:"next_step_after,omitempty"`
}

func (m *FUOTADeployment) Reset()                    { *m = FUOTADeployment{} }
func (m *FUOTADeployment) String() string            { return proto.CompactTextString(m) }
func (*FUOTADeployment) ProtoMessage()               {}
func (*FUOTADeployment) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{0} }

func (m *FUOTADeployment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FUOTADeployment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FUOTADeployment) GetGroupType() MulticastGroupType {
	if m != nil {
		return m.GroupType
	}
	return MulticastGroupType_CLASS_C
}

func (m *FUOTADeployment) GetDr() uint32 {
	if m != nil {
		return m.Dr
	}
	return 0
}

func (m *FUOTADeployment) GetFrequency() uint32 {
	if m != nil {
		return m.Frequency
	}
	return 0
}

func (m *FUOTADeployment) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *FUOTADeployment) GetRedundancy() uint32 {
	if m != nil {
		return m.Redundancy
	}
	return 0
}

func (m *FUOTADeployment) GetMulticastTimeout() uint32 {
	if m != nil {
		return m.MulticastTimeout
	}
	return 0
}

func (m *FUOTADeployment) GetUnicastTimeout() *google_protobuf3.Duration {
	if m != nil {
		return m.UnicastTimeout
	}
	return nil
}

func (m *FUOTADeployment) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *FUOTADeployment) GetNextStepAfter() *google_protobuf1.Timestamp {
	if m != nil {
		return m.NextStepAfter
	}
	return nil
}

type FUOTADeploymentListItem struct {
	// ID of the deployment (string formatted UUID).
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// Created at timestamp.
	CreatedAt *google_protobuf1.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	// Last update timestamp.
	UpdatedAt *google_protobuf1.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	// Name of the deployment.
	Name string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	// Deployment state.
	State string `protobuf:"bytes,5,opt,name=state" json:"state,omitempty"`
	// Next step after.
	NextStepAfter *google_protobuf1.Timestamp `protobuf:"bytes,6,opt,name=next_step_after,json=nextStepAfter" json:"next_step_after,omitempty"`
}

func (m *FUOTADeploymentListItem) Reset()                    { *m = FUOTADeploymentListItem{} }
func (m *FUOTADeploymentListItem) String() string            { return proto.CompactTextString(m) }
func (*FUOTADeploymentListItem) ProtoMessage()               {}
func (*FUOTADeploymentListItem) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{1} }

func (m *FUOTADeploymentListItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FUOTADeploymentListItem) GetCreatedAt() *google_protobuf1.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *FUOTADeploymentListItem) GetUpdatedAt() *google_protobuf1.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *FUOTADeploymentListItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FUOTADeploymentListItem) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *FUOTADeploymentListItem) GetNextStepAfter() *google_protobuf1.Timestamp {
	if m != nil {
		return m.NextStepAfter
	}
	return nil
}

type CreateFUOTADeploymentForDeviceRequest struct {
	// Device EUI (HEX encoded).
	DevEui string `protobuf:"bytes,1,opt,name=dev_eui,json=devEUI" json:"dev_eui,omitempty"`
	// FUOTA deployment.
	FuotaDeployment *FUOTADeployment `protobuf:"bytes,2,opt,name=fuota_deployment,json=fuotaDeployment" json:"fuota_deployment,omitempty"`
}

func (m *CreateFUOTADeploymentForDeviceRequest) Reset()         { *m = CreateFUOTADeploymentForDeviceRequest{} }
func (m *CreateFUOTADeploymentForDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*CreateFUOTADeploymentForDeviceRequest) ProtoMessage()    {}
func (*CreateFUOTADeploymentForDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor13, []int{2}
}

func (m *CreateFUOTADeploymentForDeviceRequest) GetDevEui() string {
	if m != nil {
		return m.DevEui
	}
	return ""
}

func (m *CreateFUOTADeploymentForDeviceRequest) GetFuotaDeployment() *FUOTADeployment {
	if m != nil {
		return m.FuotaDeployment
	}
	return nil
}

type CreateFUOTADeploymentForDeviceResponse struct {
	// ID of the created deployment (string formatted UUID).
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *CreateFUOTADeploymentForDeviceResponse) Reset() {
	*m = CreateFUOTADeploymentForDeviceResponse{}
}
func (m *CreateFUOTADeploymentForDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*CreateFUOTADeploymentForDeviceResponse) ProtoMessage()    {}
func (*CreateFUOTADeploymentForDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor13, []int{3}
}

func (m *CreateFUOTADeploymentForDeviceResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetFUOTADeploymentRequest struct {
	// ID of the deployment (string formatted UUID).
	// This value will be automatically assigned on create.
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetFUOTADeploymentRequest) Reset()                    { *m = GetFUOTADeploymentRequest{} }
func (m *GetFUOTADeploymentRequest) String() string            { return proto.CompactTextString(m) }
func (*GetFUOTADeploymentRequest) ProtoMessage()               {}
func (*GetFUOTADeploymentRequest) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{4} }

func (m *GetFUOTADeploymentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetFUOTADeploymentResponse struct {
	FuotaDeployment *FUOTADeployment `protobuf:"bytes,1,opt,name=fuota_deployment,json=fuotaDeployment" json:"fuota_deployment,omitempty"`
	// Created at timestamp.
	CreatedAt *google_protobuf1.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	// Last update timestamp.
	UpdatedAt *google_protobuf1.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
}

func (m *GetFUOTADeploymentResponse) Reset()                    { *m = GetFUOTADeploymentResponse{} }
func (m *GetFUOTADeploymentResponse) String() string            { return proto.CompactTextString(m) }
func (*GetFUOTADeploymentResponse) ProtoMessage()               {}
func (*GetFUOTADeploymentResponse) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{5} }

func (m *GetFUOTADeploymentResponse) GetFuotaDeployment() *FUOTADeployment {
	if m != nil {
		return m.FuotaDeployment
	}
	return nil
}

func (m *GetFUOTADeploymentResponse) GetCreatedAt() *google_protobuf1.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *GetFUOTADeploymentResponse) GetUpdatedAt() *google_protobuf1.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type ListFUOTADeploymentRequest struct {
	// Max number of deployments to return in the result-set.
	Limit int64 `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	// Offset in the result-set (for pagination).
	Offset int64 `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	// Application ID to filter on (optional).
	ApplicationId int64 `protobuf:"varint,3,opt,name=application_id,json=applicationID" json:"application_id,omitempty"`
	// Device EUI (HEX encoded) (optional).
	DevEui string `protobuf:"bytes,4,opt,name=dev_eui,json=devEUI" json:"dev_eui,omitempty"`
}

func (m *ListFUOTADeploymentRequest) Reset()                    { *m = ListFUOTADeploymentRequest{} }
func (m *ListFUOTADeploymentRequest) String() string            { return proto.CompactTextString(m) }
func (*ListFUOTADeploymentRequest) ProtoMessage()               {}
func (*ListFUOTADeploymentRequest) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{6} }

func (m *ListFUOTADeploymentRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListFUOTADeploymentRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListFUOTADeploymentRequest) GetApplicationId() int64 {
	if m != nil {
		return m.ApplicationId
	}
	return 0
}

func (m *ListFUOTADeploymentRequest) GetDevEui() string {
	if m != nil {
		return m.DevEui
	}
	return ""
}

type ListFUOTADeploymentResponse struct {
	// Total number of deployments available within the result-set.
	TotalCount int64 `protobuf:"varint,1,opt,name=total_count,json=totalCount" json:"total_count,omitempty"`
	// Deployments within this result-set.
	Result []*FUOTADeploymentListItem `protobuf:"bytes,2,rep,name=result" json:"result,omitempty"`
}

func (m *ListFUOTADeploymentResponse) Reset()                    { *m = ListFUOTADeploymentResponse{} }
func (m *ListFUOTADeploymentResponse) String() string            { return proto.CompactTextString(m) }
func (*ListFUOTADeploymentResponse) ProtoMessage()               {}
func (*ListFUOTADeploymentResponse) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{7} }

func (m *ListFUOTADeploymentResponse) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *ListFUOTADeploymentResponse) GetResult() []*FUOTADeploymentListItem {
	if m != nil {
		return m.Result
	}
	return nil
}

type ListFUOTADeploymentDevicesRequest struct {
	// ID of the deployment (string formatted UUID).
	// This value will be automatically assigned on create.
	FuotaDeploymentId string `protobuf:"bytes,1,opt,name=fuota_deployment_id,json=fuotaDeploymentID" json:"fuota_deployment_id,omitempty"`
	// Max number of items to return.
	Limit int64 `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
	// Offset in the result-set (for pagination).
	Offset int64 `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
}

func (m *ListFUOTADeploymentDevicesRequest) Reset()         { *m = ListFUOTADeploymentDevicesRequest{} }
func (m *ListFUOTADeploymentDevicesRequest) String() string { return proto.CompactTextString(m) }
func (*ListFUOTADeploymentDevicesRequest) ProtoMessage()    {}
func (*ListFUOTADeploymentDevicesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor13, []int{8}
}

func (m *ListFUOTADeploymentDevicesRequest) GetFuotaDeploymentId() string {
	if m != nil {
		return m.FuotaDeploymentId
	}
	return ""
}

func (m *ListFUOTADeploymentDevicesRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListFUOTADeploymentDevicesRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type GetFUOTADeploymentDeviceRequest struct {
	// ID of the deployment (string formatted UUID).
	// This value will be automatically assigned on create.
	FuotaDeploymentId string `protobuf:"bytes,1,opt,name=fuota_deployment_id,json=fuotaDeploymentID" json:"fuota_deployment_id,omitempty"`
	// Device EUI (HEX encoded).
	DevEui string `protobuf:"bytes,2,opt,name=dev_eui,json=devEUI" json:"dev_eui,omitempty"`
}

func (m *GetFUOTADeploymentDeviceRequest) Reset()         { *m = GetFUOTADeploymentDeviceRequest{} }
func (m *GetFUOTADeploymentDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*GetFUOTADeploymentDeviceRequest) ProtoMessage()    {}
func (*GetFUOTADeploymentDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor13, []int{9}
}

func (m *GetFUOTADeploymentDeviceRequest) GetFuotaDeploymentId() string {
	if m != nil {
		return m.FuotaDeploymentId
	}
	return ""
}

func (m *GetFUOTADeploymentDeviceRequest) GetDevEui() string {
	if m != nil {
		return m.DevEui
	}
	return ""
}

type GetFUOTADeploymentDeviceResponse struct {
	DeploymentDevice *FUOTADeploymentDeviceListItem `protobuf:"bytes,1,opt,name=deployment_device,json=deploymentDevice" json:"deployment_device,omitempty"`
}

func (m *GetFUOTADeploymentDeviceResponse) Reset()         { *m = GetFUOTADeploymentDeviceResponse{} }
func (m *GetFUOTADeploymentDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*GetFUOTADeploymentDeviceResponse) ProtoMessage()    {}
func (*GetFUOTADeploymentDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor13, []int{10}
}

func (m *GetFUOTADeploymentDeviceResponse) GetDeploymentDevice() *FUOTADeploymentDeviceListItem {
	if m != nil {
		return m.DeploymentDevice
	}
	return nil
}

type ListFUOTADeploymentDevicesResponse struct {
	// Total number of devices for the FUOTA deployment.
	TotalCount int64                            `protobuf:"varint,1,opt,name=total_count,json=totalCount" json:"total_count,omitempty"`
	Result     []*FUOTADeploymentDeviceListItem `protobuf:"bytes,2,rep,name=result" json:"result,omitempty"`
}

func (m *ListFUOTADeploymentDevicesResponse) Reset()         { *m = ListFUOTADeploymentDevicesResponse{} }
func (m *ListFUOTADeploymentDevicesResponse) String() string { return proto.CompactTextString(m) }
func (*ListFUOTADeploymentDevicesResponse) ProtoMessage()    {}
func (*ListFUOTADeploymentDevicesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor13, []int{11}
}

func (m *ListFUOTADeploymentDevicesResponse) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *ListFUOTADeploymentDevicesResponse) GetResult() []*FUOTADeploymentDeviceListItem {
	if m != nil {
		return m.Result
	}
	return nil
}

type FUOTADeploymentDeviceListItem struct {
	// Device EUI (HEX encoded).
	DevEui string `protobuf:"bytes,1,opt,name=dev_eui,json=devEUI" json:"dev_eui,omitempty"`
	// Device name.
	DeviceName string `protobuf:"bytes,2,opt,name=device_name,json=deviceName" json:"device_name,omitempty"`
	// Device state.
	State FUOTADeploymentDeviceState `protobuf:"varint,3,opt,name=state,enum=api.FUOTADeploymentDeviceState" json:"state,omitempty"`
	// Error message (in case of error state).
	ErrorMessage string `protobuf:"bytes,4,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
	// Created at timestamp.
	CreatedAt *google_protobuf1.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	// Updated at timestamp.
	UpdatedAt *google_protobuf1.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
}

func (m *FUOTADeploymentDeviceListItem) Reset()                    { *m = FUOTADeploymentDeviceListItem{} }
func (m *FUOTADeploymentDeviceListItem) String() string            { return proto.CompactTextString(m) }
func (*FUOTADeploymentDeviceListItem) ProtoMessage()               {}
func (*FUOTADeploymentDeviceListItem) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{12} }

func (m *FUOTADeploymentDeviceListItem) GetDevEui() string {
	if m != nil {
		return m.DevEui
	}
	return ""
}

func (m *FUOTADeploymentDeviceListItem) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *FUOTADeploymentDeviceListItem) GetState() FUOTADeploymentDeviceState {
	if m != nil {
		return m.State
	}
	return FUOTADeploymentDeviceState_PENDING
}

func (m *FUOTADeploymentDeviceListItem) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *FUOTADeploymentDeviceListItem) GetCreatedAt() *google_protobuf1.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *FUOTADeploymentDeviceListItem) GetUpdatedAt() *google_protobuf1.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*FUOTADeployment)(nil), "api.FUOTADeployment")
	proto.RegisterType((*FUOTADeploymentListItem)(nil), "api.FUOTADeploymentListItem")
	proto.RegisterType((*CreateFUOTADeploymentForDeviceRequest)(nil), "api.CreateFUOTADeploymentForDeviceRequest")
	proto.RegisterType((*CreateFUOTADeploymentForDeviceResponse)(nil), "api.CreateFUOTADeploymentForDeviceResponse")
	proto.RegisterType((*GetFUOTADeploymentRequest)(nil), "api.GetFUOTADeploymentRequest")
	proto.RegisterType((*GetFUOTADeploymentResponse)(nil), "api.GetFUOTADeploymentResponse")
	proto.RegisterType((*ListFUOTADeploymentRequest)(nil), "api.ListFUOTADeploymentRequest")
	proto.RegisterType((*ListFUOTADeploymentResponse)(nil), "api.ListFUOTADeploymentResponse")
	proto.RegisterType((*ListFUOTADeploymentDevicesRequest)(nil), "api.ListFUOTADeploymentDevicesRequest")
	proto.RegisterType((*GetFUOTADeploymentDeviceRequest)(nil), "api.GetFUOTADeploymentDeviceRequest")
	proto.RegisterType((*GetFUOTADeploymentDeviceResponse)(nil), "api.GetFUOTADeploymentDeviceResponse")
	proto.RegisterType((*ListFUOTADeploymentDevicesResponse)(nil), "api.ListFUOTADeploymentDevicesResponse")
	proto.RegisterType((*FUOTADeploymentDeviceListItem)(nil), "api.FUOTADeploymentDeviceListItem")
	proto.RegisterEnum("api.FUOTADeploymentDeviceState", FUOTADeploymentDeviceState_name, FUOTADeploymentDeviceState_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for FUOTADeploymentService service

type FUOTADeploymentServiceClient interface {
	// CreateForDevice creates a deployment for the given DevEUI.
	CreateForDevice(ctx context.Context, in *CreateFUOTADeploymentForDeviceRequest, opts ...grpc.CallOption) (*CreateFUOTADeploymentForDeviceResponse, error)
	// Get returns the fuota deployment for the given id.
	Get(ctx context.Context, in *GetFUOTADeploymentRequest, opts ...grpc.CallOption) (*GetFUOTADeploymentResponse, error)
	// List lists the fuota deployments.
	List(ctx context.Context, in *ListFUOTADeploymentRequest, opts ...grpc.CallOption) (*ListFUOTADeploymentResponse, error)
	// GetDeploymentDevice returns the deployment device.
	GetDeploymentDevice(ctx context.Context, in *GetFUOTADeploymentDeviceRequest, opts ...grpc.CallOption) (*GetFUOTADeploymentDeviceResponse, error)
	// ListDeploymentDevices lists the devices (and status) for the given fuota deployment ID.
	ListDeploymentDevices(ctx context.Context, in *ListFUOTADeploymentDevicesRequest, opts ...grpc.CallOption) (*ListFUOTADeploymentDevicesResponse, error)
}

type fUOTADeploymentServiceClient struct {
	cc *grpc.ClientConn
}

func NewFUOTADeploymentServiceClient(cc *grpc.ClientConn) FUOTADeploymentServiceClient {
	return &fUOTADeploymentServiceClient{cc}
}

func (c *fUOTADeploymentServiceClient) CreateForDevice(ctx context.Context, in *CreateFUOTADeploymentForDeviceRequest, opts ...grpc.CallOption) (*CreateFUOTADeploymentForDeviceResponse, error) {
	out := new(CreateFUOTADeploymentForDeviceResponse)
	err := grpc.Invoke(ctx, "/api.FUOTADeploymentService/CreateForDevice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fUOTADeploymentServiceClient) Get(ctx context.Context, in *GetFUOTADeploymentRequest, opts ...grpc.CallOption) (*GetFUOTADeploymentResponse, error) {
	out := new(GetFUOTADeploymentResponse)
	err := grpc.Invoke(ctx, "/api.FUOTADeploymentService/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fUOTADeploymentServiceClient) List(ctx context.Context, in *ListFUOTADeploymentRequest, opts ...grpc.CallOption) (*ListFUOTADeploymentResponse, error) {
	out := new(ListFUOTADeploymentResponse)
	err := grpc.Invoke(ctx, "/api.FUOTADeploymentService/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fUOTADeploymentServiceClient) GetDeploymentDevice(ctx context.Context, in *GetFUOTADeploymentDeviceRequest, opts ...grpc.CallOption) (*GetFUOTADeploymentDeviceResponse, error) {
	out := new(GetFUOTADeploymentDeviceResponse)
	err := grpc.Invoke(ctx, "/api.FUOTADeploymentService/GetDeploymentDevice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fUOTADeploymentServiceClient) ListDeploymentDevices(ctx context.Context, in *ListFUOTADeploymentDevicesRequest, opts ...grpc.CallOption) (*ListFUOTADeploymentDevicesResponse, error) {
	out := new(ListFUOTADeploymentDevicesResponse)
	err := grpc.Invoke(ctx, "/api.FUOTADeploymentService/ListDeploymentDevices", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FUOTADeploymentService service

type FUOTADeploymentServiceServer interface {
	// CreateForDevice creates a deployment for the given DevEUI.
	CreateForDevice(context.Context, *CreateFUOTADeploymentForDeviceRequest) (*CreateFUOTADeploymentForDeviceResponse, error)
	// Get returns the fuota deployment for the given id.
	Get(context.Context, *GetFUOTADeploymentRequest) (*GetFUOTADeploymentResponse, error)
	// List lists the fuota deployments.
	List(context.Context, *ListFUOTADeploymentRequest) (*ListFUOTADeploymentResponse, error)
	// GetDeploymentDevice returns the deployment device.
	GetDeploymentDevice(context.Context, *GetFUOTADeploymentDeviceRequest) (*GetFUOTADeploymentDeviceResponse, error)
	// ListDeploymentDevices lists the devices (and status) for the given fuota deployment ID.
	ListDeploymentDevices(context.Context, *ListFUOTADeploymentDevicesRequest) (*ListFUOTADeploymentDevicesResponse, error)
}

func RegisterFUOTADeploymentServiceServer(s *grpc.Server, srv FUOTADeploymentServiceServer) {
	s.RegisterService(&_FUOTADeploymentService_serviceDesc, srv)
}

func _FUOTADeploymentService_CreateForDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFUOTADeploymentForDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FUOTADeploymentServiceServer).CreateForDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.FUOTADeploymentService/CreateForDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FUOTADeploymentServiceServer).CreateForDevice(ctx, req.(*CreateFUOTADeploymentForDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FUOTADeploymentService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFUOTADeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FUOTADeploymentServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.FUOTADeploymentService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FUOTADeploymentServiceServer).Get(ctx, req.(*GetFUOTADeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FUOTADeploymentService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFUOTADeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FUOTADeploymentServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.FUOTADeploymentService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FUOTADeploymentServiceServer).List(ctx, req.(*ListFUOTADeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FUOTADeploymentService_GetDeploymentDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFUOTADeploymentDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FUOTADeploymentServiceServer).GetDeploymentDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.FUOTADeploymentService/GetDeploymentDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FUOTADeploymentServiceServer).GetDeploymentDevice(ctx, req.(*GetFUOTADeploymentDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FUOTADeploymentService_ListDeploymentDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFUOTADeploymentDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FUOTADeploymentServiceServer).ListDeploymentDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.FUOTADeploymentService/ListDeploymentDevices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FUOTADeploymentServiceServer).ListDeploymentDevices(ctx, req.(*ListFUOTADeploymentDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FUOTADeploymentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.FUOTADeploymentService",
	HandlerType: (*FUOTADeploymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateForDevice",
			Handler:    _FUOTADeploymentService_CreateForDevice_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _FUOTADeploymentService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _FUOTADeploymentService_List_Handler,
		},
		{
			MethodName: "GetDeploymentDevice",
			Handler:    _FUOTADeploymentService_GetDeploymentDevice_Handler,
		},
		{
			MethodName: "ListDeploymentDevices",
			Handler:    _FUOTADeploymentService_ListDeploymentDevices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fuotaDeployment.proto",
}

func init() { proto.RegisterFile("fuotaDeployment.proto", fileDescriptor13) }

var fileDescriptor13 = []byte{
	// 1027 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0x4f, 0x6f, 0xe3, 0x44,
	0x14, 0xc7, 0x76, 0x93, 0x92, 0x97, 0x6d, 0x9b, 0xce, 0x76, 0x5b, 0xd7, 0xdb, 0x6d, 0x82, 0x97,
	0x2e, 0x51, 0xab, 0x4d, 0xa4, 0xee, 0xb2, 0x82, 0x15, 0x02, 0x42, 0xd3, 0x46, 0x91, 0xd8, 0x16,
	0x39, 0xed, 0xd9, 0x9a, 0x8d, 0x27, 0x91, 0x21, 0xb1, 0x8d, 0x3d, 0xae, 0x88, 0x56, 0x3d, 0xc0,
	0x11, 0x89, 0x13, 0x1f, 0x00, 0x4e, 0x1c, 0xe0, 0xe3, 0xec, 0x57, 0xe0, 0xc0, 0xc7, 0x40, 0x33,
	0x1e, 0xa7, 0x8e, 0x63, 0x37, 0xed, 0x5e, 0xf6, 0xe6, 0x79, 0xf3, 0xfe, 0xfc, 0xe6, 0xf7, 0x7e,
	0xf3, 0xc6, 0xf0, 0x60, 0x10, 0xba, 0x14, 0xb7, 0x89, 0x37, 0x72, 0x27, 0x63, 0xe2, 0xd0, 0x86,
	0xe7, 0xbb, 0xd4, 0x45, 0x0a, 0xf6, 0x6c, 0x6d, 0x67, 0xe8, 0xba, 0xc3, 0x11, 0x69, 0x62, 0xcf,
	0x6e, 0x62, 0xc7, 0x71, 0x29, 0xa6, 0xb6, 0xeb, 0x04, 0x91, 0x8b, 0xb6, 0x4d, 0xed, 0x31, 0x09,
	0x28, 0x1e, 0x7b, 0xcd, 0xe9, 0x97, 0xd8, 0xda, 0xb2, 0x42, 0x9f, 0xfb, 0x36, 0xe3, 0x0f, 0xb1,
	0xb1, 0x31, 0x0e, 0x47, 0xd4, 0xee, 0xe3, 0x80, 0x76, 0x7c, 0x37, 0x14, 0xee, 0xfa, 0x9f, 0x0a,
	0xac, 0x9d, 0x5c, 0x9c, 0x9d, 0xb7, 0xae, 0x61, 0xa0, 0x55, 0x90, 0x6d, 0x4b, 0x95, 0x6a, 0x52,
	0xbd, 0x64, 0xc8, 0xb6, 0x85, 0x10, 0x2c, 0x39, 0x78, 0x4c, 0x54, 0x99, 0x5b, 0xf8, 0x37, 0x7a,
	0x01, 0x30, 0x64, 0x69, 0x4c, 0x3a, 0xf1, 0x88, 0xaa, 0xd4, 0xa4, 0xfa, 0xea, 0xe1, 0x56, 0x03,
	0x7b, 0x76, 0xe3, 0xd5, 0x4c, 0x99, 0xf3, 0x89, 0x47, 0x8c, 0xd2, 0x30, 0xfe, 0x64, 0xb9, 0x2d,
	0x5f, 0x5d, 0xaa, 0x49, 0xf5, 0x15, 0x43, 0xb6, 0x7c, 0xb4, 0x03, 0xa5, 0x81, 0x4f, 0x7e, 0x0c,
	0x89, 0xd3, 0x9f, 0xa8, 0x05, 0x6e, 0xbe, 0x36, 0x20, 0x15, 0x96, 0x3d, 0x3c, 0x19, 0xb9, 0xd8,
	0x52, 0x8b, 0x35, 0xa9, 0x7e, 0xcf, 0x88, 0x97, 0x68, 0x17, 0xc0, 0x27, 0x56, 0xe8, 0x58, 0x98,
	0x05, 0x2e, 0xf3, 0xc0, 0x84, 0x05, 0x1d, 0xc0, 0xfa, 0xf4, 0xbc, 0x26, 0xe3, 0xc8, 0x0d, 0xa9,
	0xfa, 0x21, 0x77, 0xab, 0x4c, 0x37, 0xce, 0x23, 0x3b, 0xfa, 0x06, 0xd6, 0x42, 0x67, 0xd6, 0xb5,
	0x54, 0x93, 0xea, 0xe5, 0xc3, 0xed, 0x46, 0xd4, 0x86, 0x88, 0xac, 0xd7, 0xe1, 0xa0, 0xd1, 0x16,
	0xa4, 0x1a, 0xab, 0x22, 0x22, 0xce, 0xb1, 0x01, 0x85, 0x80, 0x62, 0x4a, 0x54, 0xe0, 0x2c, 0x45,
	0x0b, 0x96, 0xd9, 0x21, 0x3f, 0x51, 0x33, 0xa0, 0xc4, 0x33, 0xf1, 0x80, 0x12, 0x5f, 0x2d, 0xf3,
	0xcc, 0xda, 0x5c, 0xe6, 0xf3, 0xb8, 0x91, 0xc6, 0x0a, 0x0b, 0xe9, 0x51, 0xe2, 0xb5, 0x58, 0x80,
	0xfe, 0x9b, 0x0c, 0x5b, 0xa9, 0x16, 0x7d, 0x6b, 0x07, 0xb4, 0x4b, 0xc9, 0x78, 0xae, 0x55, 0x9f,
	0x03, 0xf4, 0x7d, 0x82, 0x29, 0xb1, 0x4c, 0x4c, 0x79, 0xc3, 0x6e, 0x2e, 0x55, 0x12, 0xde, 0x2d,
	0xca, 0x42, 0x43, 0xcf, 0x8a, 0x43, 0x95, 0xc5, 0xa1, 0xc2, 0xbb, 0x45, 0xa7, 0x02, 0x59, 0x4a,
	0x08, 0x64, 0xca, 0x47, 0x61, 0x01, 0x1f, 0xc5, 0xbb, 0xf2, 0xf1, 0xb3, 0x04, 0x7b, 0x47, 0x1c,
	0x76, 0x8a, 0x95, 0x13, 0xd7, 0x6f, 0x93, 0x4b, 0xbb, 0x4f, 0x0c, 0xa6, 0x9f, 0x80, 0xa2, 0x2d,
	0x58, 0xb6, 0xc8, 0xa5, 0x49, 0x42, 0x5b, 0x50, 0x54, 0xb4, 0xc8, 0xe5, 0xf1, 0x45, 0x17, 0x7d,
	0x05, 0x15, 0x7e, 0xf7, 0x4c, 0x6b, 0x1a, 0x2c, 0xc8, 0xda, 0xe0, 0x1a, 0x4e, 0x25, 0x36, 0xd6,
	0x52, 0x37, 0x55, 0xff, 0x0c, 0x9e, 0x2c, 0x82, 0x10, 0x78, 0xae, 0x13, 0x90, 0x74, 0x87, 0xf4,
	0x03, 0xd8, 0xee, 0x10, 0x9a, 0x2e, 0x20, 0x00, 0xa7, 0x9d, 0xdf, 0x4a, 0xa0, 0x65, 0x79, 0x8b,
	0xdc, 0x59, 0xc7, 0x90, 0xee, 0x70, 0x8c, 0xf7, 0x23, 0x17, 0xfd, 0x57, 0x09, 0x34, 0xa6, 0xe0,
	0x1c, 0x12, 0x36, 0xa0, 0x30, 0xb2, 0xc7, 0x76, 0x74, 0x14, 0xc5, 0x88, 0x16, 0x68, 0x13, 0x8a,
	0xee, 0x60, 0x10, 0x90, 0x08, 0xa6, 0x62, 0x88, 0x15, 0xda, 0x83, 0x55, 0xec, 0x79, 0x23, 0xbb,
	0xcf, 0xaf, 0xa5, 0x69, 0x5b, 0x1c, 0x8b, 0x62, 0xac, 0x24, 0xac, 0xdd, 0x76, 0x52, 0x0a, 0x4b,
	0x49, 0x29, 0xe8, 0x14, 0x1e, 0x66, 0x62, 0x11, 0x14, 0x57, 0xa1, 0x4c, 0x5d, 0x8a, 0x47, 0x66,
	0xdf, 0x0d, 0x9d, 0x18, 0x12, 0x70, 0xd3, 0x11, 0xb3, 0xa0, 0xe7, 0x50, 0xf4, 0x49, 0x10, 0x8e,
	0x18, 0x2e, 0xa5, 0x5e, 0x3e, 0xdc, 0xc9, 0x62, 0x3e, 0xbe, 0xaf, 0x86, 0xf0, 0x65, 0x1a, 0xfe,
	0x28, 0xa3, 0x6c, 0xa4, 0x9d, 0x20, 0x66, 0xa2, 0x01, 0xf7, 0xd3, 0xfd, 0x35, 0xa7, 0xfa, 0x58,
	0x4f, 0x35, 0xb3, 0xdb, 0xbe, 0x66, 0x4e, 0xce, 0x66, 0x4e, 0x49, 0x32, 0xa7, 0x7f, 0x0f, 0xd5,
	0x79, 0x6d, 0xcd, 0x5e, 0xa0, 0xbb, 0x02, 0x48, 0xb0, 0x2c, 0xcf, 0xb0, 0x1c, 0x40, 0x2d, 0xbf,
	0x96, 0xa0, 0xfa, 0x0c, 0xd6, 0x13, 0x65, 0x2c, 0xbe, 0x29, 0xe4, 0xac, 0x67, 0x91, 0x1a, 0x85,
	0x4f, 0xa9, 0xad, 0x58, 0xa9, 0x1d, 0x46, 0xb2, 0x7e, 0x13, 0xc9, 0xb7, 0x6d, 0xf1, 0xcb, 0x54,
	0x8b, 0x6f, 0x83, 0x26, 0x6e, 0xf4, 0x3f, 0x32, 0x3c, 0xba, 0xd1, 0x33, 0x7f, 0x48, 0x55, 0xa1,
	0x1c, 0x91, 0x60, 0x26, 0x5e, 0x5f, 0x88, 0x4c, 0xa7, 0x6c, 0xc4, 0x7e, 0x1a, 0x8f, 0xd8, 0xe8,
	0xf9, 0xad, 0xe6, 0xc3, 0xea, 0x31, 0xb7, 0x78, 0x06, 0x3f, 0x86, 0x15, 0xe2, 0xfb, 0xae, 0x6f,
	0x8e, 0x49, 0x10, 0xe0, 0x61, 0x3c, 0xb6, 0xef, 0x71, 0xe3, 0xab, 0xc8, 0x96, 0x9a, 0x0c, 0x85,
	0x77, 0x9f, 0x0c, 0xc5, 0x3b, 0x4c, 0x86, 0xfd, 0x16, 0x68, 0xf9, 0xf8, 0x51, 0x19, 0x96, 0xbf,
	0x3b, 0x3e, 0x6d, 0x77, 0x4f, 0x3b, 0x95, 0x0f, 0xd8, 0xa2, 0x77, 0x71, 0x74, 0x74, 0xdc, 0xeb,
	0x55, 0x24, 0x54, 0x82, 0xc2, 0xb1, 0x61, 0x9c, 0x19, 0x15, 0xf9, 0xf0, 0xbf, 0x02, 0x6c, 0xa6,
	0x72, 0xf4, 0x88, 0xcf, 0x92, 0xa0, 0x3f, 0x24, 0x58, 0x13, 0x53, 0x3b, 0x1e, 0xd3, 0x68, 0x9f,
	0x93, 0x76, 0xab, 0xe7, 0x44, 0x3b, 0xb8, 0x95, 0x6f, 0xa4, 0x2a, 0xfd, 0xd9, 0x2f, 0x6f, 0xff,
	0xfd, 0x5d, 0x7e, 0xaa, 0xd7, 0xf9, 0x2f, 0x5c, 0xd4, 0xb5, 0xa0, 0xf9, 0x46, 0xb4, 0xfa, 0xaa,
	0xc9, 0x2f, 0xcf, 0xd3, 0x6b, 0xcd, 0x06, 0x2f, 0xa5, 0x7d, 0xf4, 0x03, 0x28, 0x1d, 0x42, 0xd1,
	0x2e, 0x2f, 0x94, 0xfb, 0x4c, 0x68, 0xd5, 0xdc, 0x7d, 0x51, 0xfc, 0x31, 0x2f, 0xfe, 0x08, 0x3d,
	0xe4, 0xc5, 0xe7, 0x4a, 0x35, 0xdf, 0xd8, 0xd6, 0x15, 0xb2, 0x61, 0x89, 0x89, 0x10, 0x45, 0xd9,
	0xf2, 0x07, 0xb2, 0x56, 0xcb, 0x77, 0x10, 0xf5, 0x76, 0x79, 0x3d, 0x15, 0x6d, 0x66, 0xd7, 0x43,
	0x7f, 0x4b, 0x70, 0xbf, 0x43, 0x68, 0xba, 0xad, 0xe8, 0xe3, 0x9c, 0x83, 0xcc, 0xf2, 0xbe, 0xb7,
	0xc0, 0x4b, 0x80, 0x38, 0xe1, 0x20, 0xbe, 0x46, 0x5f, 0xe6, 0x1d, 0x3a, 0x63, 0x94, 0x5d, 0xcd,
	0x77, 0x06, 0xfd, 0x25, 0xc1, 0x03, 0x76, 0xd8, 0xb9, 0x89, 0x81, 0x9e, 0xe4, 0x11, 0x31, 0x3b,
	0xb7, 0xb5, 0x4f, 0x16, 0xfa, 0x09, 0xc8, 0x5f, 0x70, 0xc8, 0x2f, 0xd0, 0xf3, 0x77, 0x81, 0xfc,
	0xba, 0xc8, 0x2f, 0xd3, 0xb3, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x8a, 0x6d, 0xb8, 0x3d, 0x48,
	0x0c, 0x00, 0x00,
}
